#!/usr/bin/perl -w
# $Id$
# This script converts the cvs dump of Atlantis to the schueler.txt format
#
# This script might be updated after installing an sophomorix-base package.
# You must copy it by hand to its location and adjust the configuration.
#
#
# Fetch data from Atlantis the following way:
#
#   0. Atlantis starten
#   1. Button "Schüler aktuelles Schuljahr"
#   1. Zeugnis*???? -> leeres Feld  
#   2. Schüler: *
#      Suche Starten
#        => Anzeige füllt sich
#   3. Button: Exportieren Textformat/Excel
       
#
#
#   Testen:
#    1) Aufruf von 
#         sophomorix-check --filter-only
#    2) Die gefilterte Datei liegt in
#         /var/lib/sophomorix/tmp/schueler.txt.filter.tmp  
#
# In case of Problems:
# jeffbeck@web.de  or  jeffbeck@gmx.de
#


############################################################
# Start configure 
############################################################

# number of semicolons in each line
# script returns error if this is not correct in EACH line
# key: number of selicolons
# value: max allowed number
my %semicolons_allowed = qw(
    244     3500
    255     20 
);


# do you want to try to dump the unique id
# 0: do NOT dump
# 1: dump it!
my $dump_id=0;


############################################################
# End configure 
############################################################

# keep this settings
my $tmp="/var/lib/sophomorix/tmp/schueler.txt.filter.tmp";
my $source="/etc/sophomorix/user/schueler.txt";
my $target="/var/lib/sophomorix/tmp/schueler.txt.tmp";
my %semicolons_seen=();

############################################################
# Pre-Filter
############################################################
# copy the file, when the original seems corect
my $prefilter_error=0;
open(SOURCE, "<$source") || die "Fehler: $! $source not found!"; 
while (<SOURCE>){
    my $semicolons_per_line=tr/;//;
    if (not $semicolons_per_line==4){
        $prefilter_error=1;
        #print "SEM: $semicolons_per_line\n";
    }
}

close(SOURCE);

if ($prefilter_error==0){
    print "All Lines contain 4 semicolons\n";
    print "I consider the file correct without filtering it\n\n";
    print "Copying the file without modification\n\n";
    system("cp $source $target");
    print "Last message from filter script: ended regularly\n";
    exit 0;
} else {
    print "\nPrefilter: file must be filtered!\n\n";
}

############################################################
# Filter
############################################################

open(SOURCE, "<$source") || die "Fehler: $! $source not found!"; 
open(TMP, ">$tmp") || die "Fehler: $! $tmp not found!"; 

my %header=();
my $line_num=0;
while (<SOURCE>){
    chomp();
    my @line=split(";");
    my $field_num=0;

    if($line_num==0 and $line[5] eq "Klasse"){
        # read the headers
        foreach my $item (@line){
            $header{$field_num}="$item";
            $field_num++;
        }    
        $line_num++;
        next;
    }

    if($line_num==300){
        print "Line ${line_num}:\n";
        foreach my $item (@line){
	    #print "$field_num ($header{$field_num})  $item   \n";
            printf "|%4s | %-28s| %-43s|\n",$field_num,$header{$field_num},$item;
            $field_num++;
        }
    }

    my $name=$line[1];
    my $lastname=$line[28];
    my $firstname=$line[29];
    my $birthday=$line[2];
    my $class=$line[5];
    # 13 Klassenlehrer
    my $id_0=$line[63]; # Externe ID:  -id
    my $id_1=$line[57]; # Barcode   :  ABCid
    my $id_2=$line[70]; # Externe ID Behinderungsart:  -id
    my $id_3=$line[72]; # Externe ID GS Empfehlung:  -id

    $lastname = &format_field($lastname);
    $firstname = &format_field($firstname);

    my $semicolons_per_line=tr/;//;

    my $old_num=$semicolons_seen{$semicolons_per_line};
    if (not defined $old_num){
       $old_num=0;        
    }
    my $new_num=$old_num+1;
    $semicolons_seen{$semicolons_per_line}="$new_num";

    if (not exists $semicolons_allowed{$semicolons_per_line}){ 
        print "ERROR: Line with unallowed number of semicolons: ",
              "$semicolons_per_line \n"; 
        print "$_"; 
    }

    $lastname="" if not defined $lastname;
    $firstname="" if not defined $firstname;


    my $out_line;
    if ($dump_id==0){
        $out_line = $class.";".$lastname.";".$firstname.";".$birthday.";\n";
    } elsif ($dump_id==1){
        $out_line = $class.";".$lastname.";".$firstname.";".$birthday.";".$id_0.";\n";
    } else {
        print "Could not dump into file\n\n";
        exit;
    }
    print TMP "$out_line";

    $line_num++;
}

close(SOURCE);
close(TMP);


# check if file was correct
my $error=0;

while ( ($semi, $seminum) = each %semicolons_seen ){
    my $line_err=0;
    my $print_semicolons_allowed=$semicolons_allowed{$semi};
    if(not defined $print_semicolons_allowed){
        $print_semicolons_allowed=0;
    }
    printf "   I have seen %6s of allowed %6s lines with %3s semicolons: ",
      $seminum,
      $print_semicolons_allowed,
      $semi;
    if (not exists $semicolons_allowed{$semi}){
	$error++;
        $line_err=1;
    } else {
        # correct
    }

    if ($seminum <= $print_semicolons_allowed){
        # correct
    } else {
	$error++;
        $line_err=1;
    }


 
    if ($line_err==0){
        print "CORRECT!\n";
    } else {
        print "ERROR!\n";
    }
}
print "\n";



if ($error==0){
    # exit regularly
    system("cp $tmp $target");
    #system("rm $tmp");
    print "Last message from filter script: ended regularly\n";
    exit 0;
} else {
    # exit with error
    print "Last message from filter script: ended with ERROR!\n";
    exit 1;
}





############################################################
# subs
############################################################

sub format_field {
    my ($string) = @_;
    $string=~s/^"//;
    $string=~s/"$//;
    $string=~s/^ //;
    $string=~s/ $//;
    return $string;
}


