#!/bin/sh
mkdir -p /home/students/m1kk3t/treutth/__tauschen
ln -s /root /home/students/m1kk3t/treutth/__tauschen/link1
ln -s /root /home/students/m1kk3t/treutth/__tauschen/link2
ln -s /root /home/students/m1kk3t/treutth/__tauschen/link3
ln -s /root /home/students/m1kk3t/treutth/__tauschen/link4
ln -s /root /home/students/m1kk3t/treutth/__tauschen/link5
ln -s /root /home/students/m1kk3t/treutth/__tauschen/link6


mkdir -p /home/students/m1kk3t/treutth/__tauschen/dir1
mkdir -p /home/students/m1kk3t/treutth/__tauschen/dir2
mkdir -p /home/students/m1kk3t/treutth/__tauschen/private
touch /home/students/m1kk3t/treutth/__tauschen/private/test


mkdir -p /home/students/m1kk3t/treutth/__vorlagen
ln -s /root /home/students/m1kk3t/treutth/__vorlagen/link01
ln -s /root /home/students/m1kk3t/treutth/__vorlagen/link02
ln -s /root /home/students/m1kk3t/treutth/__vorlagen/link03
ln -s /root /home/students/m1kk3t/treutth/__vorlagen/link04
ln -s /root /home/students/m1kk3t/treutth/__vorlagen/link05
ln -s /root /home/students/m1kk3t/treutth/__vorlagen/link06


mkdir -p /home/students/m1kk3t/treutth/__vorlagen/dir01
mkdir -p /home/students/m1kk3t/treutth/__vorlagen/dir02
mkdir -p /home/students/m1kk3t/treutth/__tauschen/zeugs
touch /home/students/m1kk3t/treutth/__tauschen/zeugs/test2



mkdir -p /home/students/m1kk3t/selingjo/__tauschen
ln -s /root /home/students/m1kk3t/selingjo/__tauschen/linkx1
ln -s /root /home/students/m1kk3t/selingjo/__tauschen/linkx2
ln -s /root /home/students/m1kk3t/selingjo/__tauschen/linkx3
ln -s /root /home/students/m1kk3t/selingjo/__tauschen/linkx4
ln -s /root /home/students/m1kk3t/selingjo/__tauschen/linkx5
ln -s /root /home/students/m1kk3t/selingjo/__tauschen/linkx6


mkdir -p /home/students/m1kk3t/selingjo/__tauschen/dirx1
mkdir -p /home/students/m1kk3t/selingjo/__tauschen/dirx2
mkdir -p /home/students/m1kk3t/selingjo/__tauschen/privatex
touch /home/students/m1kk3t/selingjo/__tauschen/privatex/testx


mkdir -p /home/students/m1kk3t/selingjo/__vorlagen
ln -s /root /home/students/m1kk3t/selingjo/__vorlagen/linkx01
ln -s /root /home/students/m1kk3t/selingjo/__vorlagen/linkx02
ln -s /root /home/students/m1kk3t/selingjo/__vorlagen/linkx03
ln -s /root /home/students/m1kk3t/selingjo/__vorlagen/linkx04
ln -s /root /home/students/m1kk3t/selingjo/__vorlagen/linkx05
ln -s /root /home/students/m1kk3t/selingjo/__vorlagen/linkx06


mkdir -p /home/students/m1kk3t/selingjo/__vorlagen/dirx01
mkdir -p /home/students/m1kk3t/selingjo/__vorlagen/dirx02
mkdir -p /home/students/m1kk3t/selingjo/__vorlagen/zeugsx
touch /home/students/m1kk3t/selingjo/__vorlagen/zeugsx/test2x
