#!/usr/bin/perl -w
# This script is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@gmx.de

use strict;
use Text::Iconv;

############################################################
# Config
############################################################


# the utf8 master file
my $file_in="./firstnames.utf8.txt";

# target encodings
my @target_encodings=(
                     "ISO_8859-1",
                     );



############################################################
# Program
############################################################
foreach my $encoding (@target_encodings){
    # converting the utf8 file to targets
    &convert($file_in,"./firstnames.iso8859_1.txt",$encoding);
}



############################################################
# subs
############################################################

# Option
# infile
# outfile
# target_encoding
sub convert {
    my ($in,$out,$enc) = @_;
    open(IN, "$in") || die "Fehler: $! $in nicht gefunden!"; 
    open(OUT, ">$out") || die "Fehler: $! $in nicht gefunden!"; 
    while (<IN>){
        chomp();
        my $inline=$_;
        print "$inline\n";
        my $conv = Text::Iconv->new("utf8",$enc);
        my $outline = $conv->convert($inline);
        if (defined $outline){
            print "$inline --> $outline\n";
            print OUT "$outline\n";
        } else {
            print "$inline --> NOT CONVERTABLE\n";
        }
    }
    close(IN);
    close(OUT);
}
