#!/usr/bin/perl -w
# Dieses Script (sophomorix-search) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de


# This script is now sophomorix-user -s string
