#!/usr/bin/perl -w
# Dieses Script (sophomorix-class-dbi) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de


# ===========================================================================
# Bibliotheken
# ===========================================================================
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
use Sophomorix::SophomorixAPI;
use Sophomorix::SophomorixPgLdap;
use DBI;
use Net::LDAP;
#use Schedule::at;

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
# Variablen für Optionen
$Conf::log_level=1;
my $help=0;
my $info=0;
my $class="";
my $quota;
my $mailquota;
$Conf::log_level=1;

# Parsen der Optionen
my $testopt=GetOptions(
           "help|h" => \$help,
           "info|i" => \$info,
           "class|c=s" => \$class,
           "quota=s" => \$quota,
           "mailquota=i" => \$mailquota,
           "verbose|v+" => \$Conf::log_level,
          );

# Prüfen, ob Optionen erkannt wurden
&check_options($testopt);



if (not defined $quota 
    and not defined $mailquota
    and $info==0 
    and $class eq ""){
    $help=1;
}


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlbeschreibung
   print('
sophomorix-class-dbi adds projects to the sophomorix database and adds users
   or groups as members to the project

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose
  -i  / --info
  -c AdminClass, / --class AdminClass 
  --quota quotastring
  --mailquota number
Please see the sophomorix-class(8) man pages for full documentation
');
   print "\n";
   exit;
}

############################################################
# config values
############################################################

&check_connections();



# --info
if ($info==1){
   &show_class_list();
   exit;
}







# --quota
if (defined $quota and $class ne ""){
       &update_class_db_entry($class,"Quota=$quota");
}


# --mailquota
#if ($mailquota!=-1 and $class ne ""){
if (defined $mailquota and $class ne ""){
    &update_class_db_entry($class,"MailQuota=$mailquota");
}



