#!/usr/bin/perl -w
# $Id$
# This script (sophomorix-reactivate) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@gmx.de



# Bibliotheken
use strict;


print('
sophomorix-reactivate is not used anymore to reactivate users.

   -> use the command sophomorix-user instead

Please see the sophomorix-user(8) man pages for full documentation
');

print "\n";


