#!/usr/bin/perl 
# $Id$
# This script (sophomorix-setup) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@gmx.de



# This Script adds directories and files that are necessary for sophomorix-base 
# It should be run as postinst

use Sophomorix::SophomorixBase; 

my @arguments = @ARGV;

print "##### sophomorix-setup is configuring the system for sophomorix-base ...\n";
&log_script_start(@arguments);
&log_script_end(@arguments);
