#!/usr/bin/perl -w
# $Id$
# Dieses Script (sophomorix-www) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de


# ===========================================================================
# Bibliotheken
# ===========================================================================
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase qw(student_public_upload
                                  check_options
                                 );
use Sophomorix::SophomorixAPI;
use Sophomorix::SophomorixPgLdap;
use DBI;
use Net::LDAP;
#use Schedule::at;

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
# Variablen für Optionen
$Conf::log_level=1;
my $help=0;
my $info=0;
$Conf::log_level=1;
my $student_public_upload="";
my $student_public_noupload="";
my $student_private_upload="";
my $student_private_noupload="";

# Parsen der Optionen
my $testopt=GetOptions(
           "help|h" => \$help,
           "info|i" => \$info,
           "verbose|v+" => \$Conf::log_level,
           "student-public-upload=s" => \$student_public_upload,
           "student-public-noupload=s" => \$student_public_noupload,
           "student-private-upload=s" => \$student_private_upload,
           "student-private-noupload=s" => \$student_private_noupload,
          );

# Prüfen, ob Optionen erkannt wurden
&check_options($testopt);




# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlbeschreibung
   print('
sophomorix-www manages access to public_html and private_html directories

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose
  -i  / --info

Managing students:
  --student-public-upload user1,user2,...
  --student-public-noupload user1,user2,...
  --student-private-upload user1,user2,...
  --student-private-noupload user1,user2,...

Please see the sophomorix-www(8) man pages for full documentation
');
   print "\n";
   exit;
}

############################################################
# config values
############################################################

&check_connections();

# --info
if ($info==1){

   exit;
}



#  --student-public-upload user1,user2,...
if ($student_public_upload ne ""){
    my @users = split(/,/,$student_public_upload);
    foreach my $user (@users){
	&Sophomorix::SophomorixBase::student_public_upload($user);
    }
}


