#!/usr/bin/perl -w
# Dieses Script (sophomorix-ipm-expand-from-address) wurde von 
# Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# Anleitung fuer ML 3.0
# 1) In /etc/horde/horde3/hooks.php folgendes eintragen:

# if (!function_exists('_prefs_hook_from_addr')) {
#     function _prefs_hook_from_addr($name = null)
#     {
#         if (is_null($name)) {
#             $name = Auth::getAuth();
#         }
#         if (!empty($name)) {
#             $cmd='sophomorix-imp-expand-from-address $name';
#             $mail=`$cmd`;
#             return (empty($mail) ? '' : $mail);
#         }
#         return '';
#     }
# }

# 2) Hook einschalten
# Folgende Zeile  zum hook 'from_addr' hinzufügen: 
#
#     'hook' => 'true',
#
# in /etc/horde/horde3/conf.php
#
# Sodass folgendes dasteht:
#
# $_prefs['from_addr'] = array(
#     'value' => '',
#     'hook' => 'true',
#     'locked' => false,
#     'shared' => true,
#    'type' => 'text',
#    'desc' =>  _("Your From: address:")
#);



# Bibliotheken
use strict;

# Einlesen der Konfigurationsdatei
#require "/usr/sbin/sophomorix-lib";

my $username="";
my $file="/etc/aliases";


$username=$ARGV[0];
my $liste=$ARGV[1];

if(not defined $username) {
   $username="";
}
if(not defined $liste) {
   $liste="";
}


if ($liste ne "liste") {
   # Einzelwert ausgeben
   my $mail=&get_mail_alias_from($username);
   print "$mail";
} else {
   # Liste ausgeben
   my @mail=&get_mail_alias_from($username, "liste");
   print "@mail";
}





sub get_mail_alias_from {
   my ($username, $param) = @_;
   if (not defined $param) {
       $param="";
   }

   my $begin_automatisch=0;
   my @liste=();
   if ($param eq "liste") {
      # jede Zeile durchsuchen, auch manuell konfigurierte
      $begin_automatisch=1;
   }

   open(ALIASES, "<$file");
      while (<ALIASES>) {
          # Erste ab dieser Zeile beginnen
          if(/^\#\#\# Entries after here are managed by sophomorix-mail/){
              #print "Found sophomorix-mail line\n";
              $begin_automatisch=1
          }

          if ($begin_automatisch==1) {
             # wenn die Automatischen Einträge erreicht sind
             s/\s//g; # Spezialzeichen raus
             if ($_ eq ""){next;} # Wenn Zeile Leer, dann aussteigen
             if(/^\#/){next;} # Bei Kommentarzeichen aussteigen
             if(not /:/){next;} # Bei fehlendem Doppelpunkt aussteigen

             # gültige Zeilen untersuchen
             my($alias, $login)=split(/:/);

             if (not defined $username) {
               # ungültige Zeile/Listenzeile/kein Parameter übergeben
                return "";
                close(ALIASES);
                exit;
             }

             if ($login eq $username) {
                #print "$alias";
	       if ($param eq "liste") {
                   push @liste, $alias;     
	       } else {
                   return $alias;
                   close(ALIASES);
                   exit; 
	      }
             }
          }

      }

   close(ALIASES);
   if ($param eq "liste") {
        return @liste;
    } else {
#	my $last=pop(@liste);
#	print "Last $last\n";
#        return $last;
        return $username
    }


}






