#!/usr/bin/perl -w
# $Id$
# Dieses Script (sophomorix-reaktivate) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de


# Bibliotheken
use strict;


print('
sophomorix-reactivate is not used anymore to reactivate users.

   -> use the command sophomorix-user instead

Please see the sophomorix-user(8) man pages for full documentation
');

print "\n";


