#!/usr/bin/perl -w
# Dieses Script (sophomorix-passwd) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# Bibliotheken
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixBase;
use Sophomorix::SophomorixAPI;


# ===========================================================================
# Loading the db-Module, list of functions
# ===========================================================================
# list of functions to load if db is 'files'
use if ${DevelConf::db_backend} eq 'files' , 
    'Sophomorix::SophomorixFiles' => qw(show_modulename
                                        get_first_password
                                        update_user_db_entry
                                       );

# list of functions to load if db is 'ldap'
use if ${DevelConf::db_backend} eq 'ldap' ,
    'Sophomorix::SophomorixLDAP' => qw(show_modulename);;



# ===========================================================================
# Loading the sys-db-Module, list of functions
# ===========================================================================
# list of functions to load if db is 'files'
use if ${DevelConf::sys_db} eq 'files' , 
    'Sophomorix::SophomorixSYSFiles' => qw(show_sys_modulename
                                          );


# show the Database Modules that are loaded
&show_modulename();
&show_sys_modulename();

# ===========================================================================
# Variables
# ==========================================================================

my %seen=();
my @userlist=();
my @unique_userlist=();

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================

# Variablen für Optionen
$DevelConf::testen=0;
$DevelConf::system=0;
$Conf::log_level=1;
my $help=0;
my $info=0;
my $loginname="";
my $groups="";
my $pupil=0;
my $rooms="";
my $ws=0;

my $password="";
my $reset=0;
my $crandom=0;
my $random=0;

# flag, if (1) user has specified ONE password for all (-p or --crandom)  , 
#    or if (2) password must be calculated for each user
my $password_given=0;

# Parsen der Optionen
my $testopt=GetOptions(
           "login|user|u|l=s" => \$loginname,
           "group|class|klasse|g|c|k=s" => \$groups,
           "pupil|pupils" => \$pupil,
           "room|=s" => \$rooms,
           "workstations|workstation|ws" => \$ws,
           "password|p=s" => \$password,
           "reset" => \$reset,
           "crandom|grandom" => \$crandom,
           "random" => \$random,
           "verbose|v+" => \$Conf::log_level,
           "info|i" => \$info,
           "help|h" => \$help
          );

# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);

# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-passwd adds users to the sophomorix database and the authentification system

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose
  -i  / --info
  -l  login1, ... / --login login1, .../ -u login1, ... / --user login1, ...
  -c class / --class class 
  --pupils
  -r room / --room room
  --workstations

Please see the sophomorix-passwd(8) man pages for full documentation
');
   print "\n";
   exit;
}


# --user
if ($loginname ne "") {
  my (@loginlist)=split(/,/,$loginname);


##?????ß prüfen auf gültigkeit

  push @userlist, @loginlist;
}


# --group
if ($groups ne "") {
  my @users=();
  my (@classlist)=split(/,/,$groups);
  foreach my $class (@classlist){
     @users=&get_user_adminclass($class);
     push @userlist, @users;
  }
}


# --pupil
if ($pupil==1) {
  my @users=();
     @users=&get_pupils_school();
     push @userlist, @users;
}


# --room
if ($rooms ne "") {
  my @users=();
  my (@roomlist)=split(/,/,$rooms);
  foreach my $room (@roomlist){
     @users=&get_workstations_room($room);
     push @userlist, @users;
  }
}


# --workstations
if ($ws==1) {
  my @users=();
     @users=&get_workstations_school();
     push @userlist, @users;
}



# remove doules/order alphabetical
foreach my $item (@userlist) {
    unless ($seen{$item}) {
        # if we get here, we have not seen it before
        $seen{$item} = 1;
        push(@unique_userlist, $item);
    } else {
        if($Conf::log_level>=3){
           print "User $item is already in the list\n";
        }
    }
    @unique_userlist = sort @unique_userlist;

}


# --info, show only the users
if ($info==1) {
   &print_list_column(6,"Passwörter setzen für user ",@unique_userlist);
   exit;
}


# exit if no users specified
if ($#userlist+1==0){
    print "ERROR: No users specified. \n";
    exit;
}

################################################################################
# Start
################################################################################

if ($password ne ""){
   $password_given=1;
}

if ($crandom==1){
    # ???????
    $password="crandom";
    $password_given=1;
}


my $random_teacher=0;
my $random_pupil=0;


print $password_given, "---\n";

foreach my $user (@unique_userlist){

    # gruppe ermitteln

    my $group=&get_klasse_von_login($user);

    # which password to set
    if ($password_given==1){
         # use $password, do nothing
    } elsif ($reset==1){
         # lookup old password
        $password=&get_first_password($user);
    } elsif ($random==1){
       # set password randomly
       
	$password="random";
     
    } else {
       print "No password option specified\n";
       # nothing specified: use sophomorix.conf
       if ($group eq "lehrer"){
          # teacher
          if ($Conf::lehrer_zufall_passwort eq "ja"){
	      $password="random";
          } else {
              $password="linux";
          }
       } else {
          # pupil
          if ($Conf::schueler_zufall_passwort eq "ja"){
	      $password="random";
          } else {
              $password="linux";
          }

       }
    }

    print "Setting password for user $user in $group to $password ...\n";

    # Passwort für user setzten
    &set_sophomorix_passwd($user,$password)
    # updating the database
    &update_user_db_entry($user,"FirstPass=$password");
    


}









