#!/usr/bin/perl -w
# $Id$
# Dieses Script (sophomorix-groupadd) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# Bibliotheken
use strict;
use Quota;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
use DBI;
use Net::LDAP;
use Sophomorix::SophomorixPgLdap qw(show_modulename
                                    check_connections
                                    db_connect
                                    db_disconnect
                                    create_user_db_entry
                                    backup_user_database
                                    set_sophomorix_passwd
                                    create_class_db_entry
                                   );

my @arguments = @ARGV;

my $zeit=&zeit_stempel();
my $pg_timestamp=&pg_timestamp();
my $gidnumber;
my $gid_force_number;
my $groupname;


# ===========================================================================
# Optionen verarbeiten
# ==========================================================================

# Variablen für Optionen
$DevelConf::testen=0;
$DevelConf::system=0;
$Conf::log_level=1;
my $help=0;


# Parsen der Optionen
my $testopt=GetOptions(
           "gidnumber|g=i" => \$gid_force_number,
           "verbose|v+" => \$Conf::log_level,
           "help|h" => \$help
          );

# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);
&log_script_start(@arguments);

# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-groupadd adds groups to the sophomorix database and the authentification system

usage: sophomorix-groupadd groupname

Options
  -g gidnumber / --gidnumber gidnumber


Please see the sophomorix-groupadd(8) man pages for full documentation
');
   print "\n";
   exit;
}

&check_connections();


# exit if arguments are bad
if (not defined $ARGV[0] or defined $ARGV[1]){
    print "ERROR\n";
    print "\n   sophomorix-groupadd needs exactly ONE argument\n\n";
    exit;
}

# neue gruppe anlegen und gidnumber holen, falls erforderlich
$gidnumber=&create_class_db_entry($ARGV[0],3,$gid_force_number);



&log_script_end(@arguments);
