#!/usr/bin/perl 
# $Id$
# Dieses Script (sophomorix-setup) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de


# This Script adds directories and files that are necessary for sophomorix-base 
# It should be run as postinst
#use Sophomorix::SophomorixConfig; 
use Sophomorix::SophomorixBase; 

# Einlesen der Konfigurationsdatei für Entwickler
#{ package DevelConf ; do "/etc/sophomorix/devel/user/sophomorix-devel.conf"}

print "##### sophomorix-setup is configuring the system for sophomorix-base ...\n";
&log_script_start();
