#!/usr/bin/perl -w
# $Id$
# Dieses Script (sophomorix-mail) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# ===========================================================================
# Bibliotheken
# ===========================================================================
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");

use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
use Sophomorix::SophomorixPgLdap qw(
                                  show_modulename
                                  db_connect
                                  db_disconnect
                                  check_connections
                                  fetchusers_from_project
                                  fetchinfo_from_project
                                  fetchusers_from_adminclass
                                   );
use DBI;
use Net::LDAP;
use IMAP::Admin;

my @arguments = @ARGV;

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
#my $gruppe="";
my $file="/etc/aliases";
my $file_tmp="/etc/aliases-tmp";
my $new_aliases="/usr/bin/newaliases";

# Variablen für Optionen
$Conf::log_level=1;
my $help=0;
my $info=0;
my $show_mailbox=0;

# Parsen der Optionen
my $testopt=GetOptions(
           "verbose|v+" => \$Conf::log_level,
           "help|h" => \$help,
           "showmailbox|showmailboxes" => \$show_mailbox,
           "info|i" => \$info
          );


# Prüfen, ob Optionen erkannt wurden
&check_options($testopt);
&log_script_start(@arguments);


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlbeschreibung
   print "\n$scriptname modifies $file and runs newaliases.\n\n";
   print "There will be added:\n";
   print "    - mailaliases (firstname.surname)\n";
   print "    - maillists (common mailadress named like group)\n";
   print "\n";
   print "The following groups are possible:\n";
   print "    - adminclass (update db with sophomorix-class ...)\n";
   print "    - projects   (update db with sophomorix-project ...)\n";
   print "    - subclass   (todo)\n";
   print "\n... then run sophomorix-mail\n";
   print('
Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose
  -i  / --info
  
Imap-Server Options
  --showmailboxes

Please see the sophomorix-mail(8) man pages for full documentation
');
   print "\n";
   exit;
}

&check_connections();


# classes with mailalias vorname.nachname
my @mail_klassen=&get_mail_alias_classes();
# classes with maillist
my @mail_liste_klassen=&get_mail_list_classes();


# projects with mailalias vorname.nachname
my @mail_projects=&get_mail_alias_projects();
# projects with maillist
my @mail_list_projects=&get_mail_list_projects();



# --info
if ($info==1) {
   print "\n";
   print "Groups, which members will have a mailalias:\n";
   print "  @mail_klassen\n\n";

   print "Groups, which have a maillist\n";
   print "  @mail_liste_klassen\n\n";

   exit;
}

if ($show_mailbox==1) {
    my $imap=&imap_connect("localhost",${DevelConf::imap_admin});
    # fetch list of mailboxes
    &imap_show_mailbox_info($imap);
    &imap_disconnect($imap);

    exit;
}



################################################################################
# Programm
################################################################################

&titel("sophomorix-mail is creating Mail-Aliases/Lists");


# ! Careful ! This string CANNOT be changed!
my $magic_line="### Add your own entries BEFORE this line ###\n";
my $magic=0;


# 1) read until magic line
open(ALIASESTMP, ">$file_tmp");
open(ALIASES, "<$file");
while (<ALIASES>) {
    my $line = $_;
    print ALIASESTMP "$line";
    if ($line eq $magic_line){
        $magic=1;
        last;
    }
}
close(ALIASES);



# 2) append magic line if necessary
if ($magic==0){
    # append magic line
    print ALIASESTMP $magic_line;
}


# 3) add own stuff
# additional comment
print ALIASESTMP "### Entries after here are managed by sophomorix-mail ###\n";

# aliases of adminclasses
foreach my $gruppe (@mail_klassen) {
   if (${Conf::mail_aliases} eq "vorname.nachname"
       or ${Conf::mail_aliases} eq "vorname_nachname") {
      print "   Generating mailaliases for adminclass $gruppe\n";
      &generate_mail_alias_classes("$gruppe"); 
  } else {
      print "Warning: ${Conf::mail_aliases} is not a valid",
            " alias template for $gruppe.\n";
  }
}


# aliases of projects
foreach my $gruppe (@mail_projects) {
   if (${Conf::mail_aliases} eq "vorname.nachname"
       or ${Conf::mail_aliases} eq "vorname_nachname") {
      print "   Generating mailaliases for project $gruppe\n";
      &generate_mail_alias_projects("$gruppe"); 
  } else {
      print "Warning: ${Conf::mail_aliases} is not a valid",
            " alias template for $gruppe.\n";
  }
}



# mailinglist of adminclass
foreach my $gruppe (@mail_liste_klassen) {
      print "   Generating mailinglist for adminclass $gruppe\n";
      &generate_maillist_classes("$gruppe"); 
}


# mailinglist of projects
foreach my $gruppe (@mail_list_projects) {
      print "   Generating mailinglist for project $gruppe\n";
      &generate_maillist_projects("$gruppe"); 
}

close(ALIASESTMP);



# replace /etc/aliases
system("mv $file_tmp $file");


# 4) run newaliases
if (-e "$new_aliases"){
    print "Running $new_aliases ... ";
    system("$new_aliases");
    print "done!\n";
} else {
    print "ERROR $new_aliases not found\n";

}


&log_script_end(@arguments);




################################################################################
# Subroutines
################################################################################

sub get_mail_alias_classes {
    my @classes=();
    my $dbh=&db_connect();
    # select the columns that i need
    my $sth= $dbh->prepare( "SELECT gid,mailalias 
                            FROM classdata 
                            WHERE (mailalias='t'
                              AND (type='adminclass' OR type='teacher')) 
                           " );
    $sth->execute();
    my $array_ref = $sth->fetchall_arrayref();
    foreach my $row (@$array_ref){
       # split the array, to give better names
       my ($gid,$mailalias)=@$row;
       push @classes, $gid;
    }
    &db_disconnect($dbh);
    return @classes;
}


sub get_mail_alias_projects {
    my @projects=();
    my $dbh=&db_connect();
    # select the columns that i need
    my $sth= $dbh->prepare( "SELECT gid,mailalias 
                            FROM projectdata 
                            WHERE mailalias='t'
                            " );
    $sth->execute();
    my $array_ref = $sth->fetchall_arrayref();
    foreach my $row (@$array_ref){
       # split the array, to give better names
       my ($gid,$mailalias)=@$row;
       push @projects, $gid;
    }
    &db_disconnect($dbh);
    return @projects;
}


sub get_mail_list_classes {
    my @classes=();
    my $dbh=&db_connect();
    # select the columns that i need
    my $sth= $dbh->prepare( "SELECT gid,maillist 
                            FROM classdata 
                            WHERE (maillist='t'
                              AND (type='adminclass' OR type='teacher')) 
                           " );
    $sth->execute();
    my $array_ref = $sth->fetchall_arrayref();
    foreach my $row (@$array_ref){
       # split the array, to give better names
       my ($gid,$maillist)=@$row;
       push @classes, $gid;
    }
    &db_disconnect($dbh);
    return @classes;
}


sub get_mail_list_projects {
    my @projects=();
    my $dbh=&db_connect();
    # select the columns that i need
    my $sth= $dbh->prepare( "SELECT gid,maillist 
                            FROM projectdata 
                            WHERE maillist='t'
                           " );
    $sth->execute();
    my $array_ref = $sth->fetchall_arrayref();
    foreach my $row (@$array_ref){
       # split the array, to give better names
       my ($gid,$maillist)=@$row;
       push @projects, $gid;
    }
    &db_disconnect($dbh);
    return @projects;
}





sub generate_mail_alias_classes {
   # generate mailaliases for all users in adminclass
   my ($group)=@_;
   my @user = &fetchusers_from_adminclass($group);
   if (defined $user[0]){
       print ALIASESTMP "\n### Mailaliases for adminclass $group \n";
       foreach my $user (@user) {
           # Gecos-Feld ermitteln
           my ($home,$type,$gecos)=
             &Sophomorix::SophomorixPgLdap::fetchdata_from_account($user);
           if (${Conf::mail_aliases} eq "vorname.nachname"){
	       $gecos=&recode_to_ascii($gecos);
               printf ALIASESTMP "%-35s %-20s \n",$gecos.":",$user;
           } elsif (${Conf::mail_aliases} eq "vorname_nachname"){
	       $gecos=&recode_to_ascii($gecos);
               printf ALIASESTMP "%-35s %-20s \n",$gecos.":",$user;
           }
       }
   }
}




sub generate_mail_alias_projects {
   # generate mailaliases for all users in project
   my ($group)=@_;
   my @user=&fetchusers_from_project($group);
   print ALIASESTMP "\n### Mailaliases for project $group \n";
   foreach my $user (@user) {
      # Gecos-Feld ermitteln
      my ($home,$type,$gecos)=
             &Sophomorix::SophomorixPgLdap::fetchdata_from_account($user);
      if (${Conf::mail_aliases} eq "vorname.nachname"){
	  $gecos=&recode_to_ascii($gecos);
          printf ALIASESTMP "%-35s %-20s \n",$gecos.":",$user;
      }elsif (${Conf::mail_aliases} eq "vorname_nachname"){
	  $gecos=&recode_to_ascii($gecos);
          printf ALIASESTMP "%-35s %-20s \n",$gecos.":",$user;
      }
   }
}




sub generate_maillist_classes {
   # generate mailinglist alias for group
   my ($group)=@_;
   my $letzter_user="";
   my $ende="";

   my @user = &fetchusers_from_adminclass($group);

   print ALIASESTMP "\n### Mailinglist for adminclass $group \n";

   if (defined $user[0]){
      # Gruppen-Mailingliste erzeugen:
      print ALIASESTMP "$group:\n";
      $ende=$#user;
      $letzter_user=$user[ $ende ];
      if($Conf::log_level>=3){
          print "User $letzter_user hat den index $ende und ist der Letzte.\n";
      }
      foreach my $user (@user) {
         print ALIASESTMP "   $user";
         if ($user eq $letzter_user){
            print ALIASESTMP "\n";
         } else {
            print ALIASESTMP ",\n"; 
         }
      } 
   }
 }



sub generate_maillist_projects {
   # generate mailinglist alias for group
   my ($group)=@_;
   my $letzter_user="";
   my $ende="";

   my @user=&fetchusers_from_project($group);
   my ($longname)=&fetchinfo_from_project($group);

   print ALIASESTMP "\n### Mailinglist for project ",
                    "$group (LongName: $longname)\n";

   if (defined $user[0]){
       # create alias from longname to name
       if ($group ne $longname){
          printf ALIASESTMP "%-35s %-20s \n",$longname.":",$group;
       }
       print ALIASESTMP "$group:\n";

       # Gruppen-Mailingliste erzeugen:
       $ende=$#user;
       $letzter_user=$user[ $ende ];
       if($Conf::log_level>=3){
          print "User $letzter_user hat den index $ende und ist der Letzte.\n";
       }
       foreach my $user (@user) {
          print ALIASESTMP "   $user";
          if ($user eq $letzter_user){
              print ALIASESTMP "\n";
          } else {
              print ALIASESTMP ",\n"; 
          }
       } 
   }
}


