### This Script contains Unix-Line-Endings
### You can edit this file with a unix-editor
###
### Diese Datei enthält Unix-Zeilentrennen
### Sie kann mit einem Unix-Editor editiert werden
###
### This template will overwrite netlogon.bat!
### Mit diesem Template wird netlogon.bat ueberschrieben


rem DO NOT EDIT THIS FILE.
rem IT WILL BE OVERWRITTEN BY SOPHOMORIX_SAMBA

rem Make your changes to common.bat!

rem DIESE DATEI NICHT AENDERN.
rem SIE WIRD VON SOPHOMORIX_SAMBA UEBERSCHRIEBEN

rem Tragen sie Ihre Aenderungen in common.bat ein!


rem @echo off
rem login-script user

rem Synchronizing the clock
net time \\$smb_netbios_name /set /yes


rem Connecting the home-share.
net use h: \\$smb_netbios_name\homes /yes 


rem Connecting the programs-share.
net use p: \\$smb_netbios_name\pgm /yes

### The administrator should make changes to common.bat
### Der Netzwerkbetreuer sollte Aenderungen in common.bat vornehmen
call \\$smb_netbios_name\common.bat

