#!/usr/bin/perl 
# Dieses Script (sophomorix-pgldap) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de


# This Script adds directories and files that are necessary for sophomorix-base 
# It should be run as postinst
use Sophomorix::SophomorixConfig; 

print "##### sophomorix-pgldap is configuring postres for sophomorix-pgldap ...\n";



print "##### sophomorix-pgldap is configuring openldap for sophomorix-pgldap ...\n";



