#!/usr/bin/perl 
# $Id$
# Dieses Script (sophomorix-dump-pg2ldap) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");


# Todo replace debconf calls with thomas values

use Sophomorix::SophomorixConfig; 
use Sophomorix::SophomorixBase; 
#use Sophomorix::SophomorixPgLdap qw(
#                                   );

my @arguments = @ARGV;



my $help=0;
my $info=0;
$Conf::log_level=1;

my $dump=0;
my $load_dump=0;
my $domainname="";
my $skiplock=0;


############################################################
# read the values from the config file
############################################################
my $config_file="/etc/sophomorix/pgldap/pgldap.conf";
if (-e $config_file) { 
   { package PgLdapConf ; do "$config_file"}
   $domainname=$PgLdapConf::domainname;
}

# domainname
#------------------------------------------------------------

my $domainname_debconf=
    &get_debconf_value("linuxmuster-base", "domainname",0);
# process debconf data
if ($domainname_debconf ne 0){
    # from debconf
    $domainname=$domainname_debconf;    
    print "   Domainname from debconf              : $domainname \n";
} else {
    # from config file
    print "   Domainname from pgldap.conf          : $domainname \n";
}


my ($basedn,$dc)=&basedn_from_domainname($domainname);
my $timestamp=&zeit_stempel();

# Parsen der Optionen
my $testopt=GetOptions(
           "verbose|v+" => \$Conf::log_level,
           "help|h" => \$help,
           "skiplock" => \$skiplock,
           "info|i" => \$info,
           "dump" => \$dump,
           "load_dump" => \$load_dump,
          );

# Prüfen, ob Optionen erkannt wurden
&check_options($testopt);
&log_script_start(@arguments);



my $dump_dir=${DevelConf::log_pfad_pg2ldif};
my $ldif_file="slapd.ldif";





# without options:
# dump and load
if ($dump==0 and $load_dump==0){
    $dump=1;
    $load_dump=1;
}




# --dump
if ($dump==1){
    # dumping
    system("mkdir -p $dump_dir");
    print "Dumping to $dump_dir...\n";
    system("dump-postgres-for-ldap.sh $dump_dir");
    # convertting to ldif
    system("gen-ldif-from-sql.perl $dump_dir $basedn > $dump_dir/$ldif_file");
} else {
    print "NOT dumping pg to ldif\n";
}



# --load
if ($load_dump==1){
    my $ldap_dir="/var/lib/ldap";
    my $db_config="/var/lib/ldap/DB_CONFIG";
    my $template=${DevelConf::config_template_pfad};
    my $ldif_local="/usr/share/sophomorix/config-templates/ldap/local-gen.ldif";

    print "Loading ldif file $dump_dir/$ldif_file\n";
    system("/etc/init.d/slapd stop");
    sleep 2;
    system("killall slapd");

    # remove bdb files from slapd
    print "throwing away old ldap tree and creating a new...\n";
    system("rm -rf /var/lib/ldap/*");
    system("cp ${template}/bdb/slapd-standalone.DB_CONFIG $db_config"); 
    system("chown openldap.openldap $ldap_dir/*"); 

    # start and stop slapd to recreate files in /var/lib/ldap
    system("/etc/init.d/slapd start");
    system("/etc/init.d/slapd stop");

    # slapd must be stopped again
    # populate ldap (no users)
    print "Populating ldap with $ldif_local\n";
    system("slapadd -c -l $ldif_local");
    system("chown openldap.openldap $ldap_dir/*"); 

    print "loading dump ...\n";
    system("slapadd -c -l $dump_dir/$ldif_file");
    system("chown openldap.openldap $ldap_dir/*"); 
    system("/etc/init.d/slapd start");
} else {
    print "NOT loading ldif into ldap\n";
}



&log_script_end(@arguments);



