#!/bin/sh
aptitude update

# tools
aptitude install emacs make diff libterm-readline-perl-perl perl-doc

# packages
aptitude install dpkg-dev fakeroot man2html docbook-utils docbook lintian debhelper devscripts
