#!/bin/sh
sudo aptitude update

# tools
sudo aptitude install emacs make diff libterm-readline-perl-perl perl-doc

# packages
sudo aptitude install dpkg-dev fakeroot man2html docbook-utils docbook lintian debhelper devscripts
