#!/usr/bin/perl -w
# $Id$
# This script is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@gmx.de



# Bibliotheken
use strict;

print "sopho-changelog: Creating the changelog for html documentation\n";


my $out_path="sophomorix-doc/html/changelog";

system("install -d $out_path");
system("cp changelog-sophomorix-src ${out_path}/changelog");

