.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOPHOMORIX-VAMPIRE 8 "February 28, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sophomorix-vampire \- Migration eines Servers auf neue Hardware und neue Software-Version
.SH SYNOPSIS
.B sophomorix-vampire
.RI [ options ]
.br
.SH WELCHE DATEN WERDEN ÜBERNOMMEN?
.TP
.B Loginnamen:
.br
Jeder Benutzer behält seinen Loginnamen/Benutzername
.TP
.B Private Userdaten:
.br
Linux-Daten im Homeverzeichnis werden nach old-data/linux
kopiert. 
.br
Windows-Daten werden nach old_data/windows kopiert.
.TP
.B Email im mbox-Format:
.br
Die Mailbox liegt im Homeverzeichnis werden in old-data/mail/loginname
.br
Windows-Daten werden nach old_data/windows kopiert.
.TP
.B Klassennamen:
.br
Achtung: aus k7a wird 7a.
.br
.SH WELCHE DATEN WERDEN NICHT ÜBERNOMMEN?
.B Veränderte Passwörter:
.br 
Jeder Benutzer bekommt wieder sein Erstpasswort (so wie auf den
Anmeldungskärtchen ausgedruckt). Veränderte Passwörter werden NICHT
übernommen.
.br
.SH DESCRIPTION
.B sophomorix-vampire  
wird auf einem neuen Server gestartet und holt dann Benutzer und und Daten eines alten Servers. 
.TP
.B Step 1:
.TP
.B (--key) Erzeugen eins ssh-keys und ablegen auf dem alten Server.
.TP
oder:
.TP
.B (--localdisk) holen der Daten von einer Wechselplatte (ToDo).
.TP
.B Step 2:
.TP
.B (--files) Konfigurationsdateien von sophomorix und dem System holen
.TP
.B Step 3:
.TP
.B (--sync-users) Benutzer mit gleichen Loginnamen anlegen
Ermitteln welche User auf dem neuen system NICHT vorhanden sind, aber auf dem alten.(dachboden-user)

.TP
.B Step 4:
.TP
.B (--sync-homes) Daten im Home der Benutzer abgleichen.
.TP
.B Step 5. Quota anlegen(Todo)
.TP
.B Step 6:
.TP
.B (--sync-workstations) Workstation-accounts anlegen.(ToDo)
.TP
.B Step 7:
.B  Synchronisieren der Klassentausch-Verzeichnisse aller Klassen des neuen Servers (ToDo)
.TP 
.TP
.B Step 8:
.TP
.B Synchronisieren sonstiger Verzeichnisse(ToDo)
   (--rembo) rembo images synchronisieren
   (--mlscripten) 
   (--myshn)
.TP 
.PP
.SH OPTIONS
.B sophomorix-vampire
benützt die GNU command line syntax, mit langen Optionen, die mit zwei
Bindestrichen (`-') beginnen:
.TP
.B -h, --help
Kurzübersicht über Optionen, sowie eine Liste der eingelesenen Dateien.
.TP
.B -v, --verbose
Sagt, was das Programm gerade macht (verbose)
.TP
.B -vv, --verbose --verbose
Sagt ungeheuer genau, was das Programm gerade macht (very verbose)
.TP
.B -i, --info
Sagt für welche User Passwörter verändert werden würden.
.TP
.B --server ip, --server name
gibt an von welchem Server die Daten geholt werden sollen. Wenn die Namensauflösung funktioniert kann auch der name des servers benutzt werden.
.TP
.B --clear
löscht das Verzeichnis /root/sophomorix-vampire in dem Konfigurationsdateien des alten Servers liegen.
.TP
.B Optionen, die angeben, wie das Passwort lauten soll:
.TP
Wenn keine dieser Option angegeben wird, dann werden die Einstellungen aus sophomorix.conf verwendet.
.TP
.B -p geheim, --password geheim
setzt das Passwort auf den Wert geheim. 
.TP
.B --common
erzeugt nach den Angaben in sophomorix.conf jeweils ein Passwort für Lehrer und eines für Schüler . Alle Lehrer bzw. Schüler bekommen dasselbe Passwort. 
.TP
Wird eine Längenangabe mit --plength num gemacht, dann wird ein Zufallspasswort generiert.
.TP
.B --reset
setzt das Passwort auf den Wert, der beim ersten Anlegen des Users gültig war. Dieser Wert wird aus der sophomorix Datenbank geholt. 
.TP
.B --random
setzt das Passwort bei Lehrern und Schülern auf einen neuen, individuellen Zufallswert. Jeder User bekommt ein eigenes Zufallspasswort. Die Länge richtet sich nach den Angaben in sophomorix.conf. 
.TP
.B --plength num
Setzt die Länge der Zufalls-Passwörter auf den Wert num. Die Länge richtet sich somit nicht mehr nach den Angaben in sophomorix.conf.  
.TP
.B Optionen die angeben von welchen Usern Daten synchronisiert werden sollen
.TP
Die Auswahl erfolgt anhäufend. Das bedeutet, dass durch Angabe mehrerer Optionen eine Userliste erzeugt wird, in der kein User doppelt vorkommt, aber jeder enthalten ist.
.TP
.B -l name1,name2, ... , --login name1, ... -u name1, ... , --user name1, ... 
setzt das Passwort der  User name1,name2, ... . Der user kann auch eine Workstation sein.
.TP
.B -c class1,class2, ... , --class class1,class2, ...
setzt das Passwort für jeden User in der Klasse class. Class kann auch die Gruppe der Lehrer sein (lehrer im Moment).
.TP
.B -p project1,project2, ... , --project project1,project2, ...
setzt das Passwort für jeden User im Project project1,.... 
.TP
.B --pupils 
setzt das Passwort für alle Schüler der Schule.
.TP
.B -r raum1,raum2, ... , --room raum1,raum2,...
setzt das Passwort für jede Workstation im raum raum1,raum2 ...
.TP
.B  --workstations 
setzt das Passwort für alle Workstations der Schule.
.TP
.SH SEE ALSO
.BR sophomorix (8),
.BR sophomorix-teach-in (8),
.BR sophomorix-add (8),
.BR sophomorix-move (8),
.BR sophomorix-print (8),
.BR sophomorix-kill (8),
.BR sophomorix-split (8),
.BR sophomorix-project (8),

.\".BR baz (1).
.\".br
.\"You can see the full options of the Programs by calling for example 
.\".IR "sophomrix-vampire -h" ,
.
.SH AUTHOR
This manual page was written by <jeffbeck@web.de>.
