.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOPHOMORIX-VAMPIRE 8 "February 28, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sophomorix-vampire \- Migration eines Servers auf neue Hardware und neue Software-Version
.SH SYNOPSIS
.B sophomorix-vampire
.RI [ options ]
.br
.SH WELCHE DATEN KÖNNEN ÜBERNOMMEN WERDEN?
.TP
.B Loginnamen:
.br
Jeder Lehrer und Schüler behält seinen Loginnamen/Benutzernamen.
.TP
.B Private Userdaten:
.br
Linux-Daten im Homeverzeichnis werden nach $HOME/old_data/linux
kopiert. 
.br
Windows-Daten werden nach $HOME/old_data/windows kopiert.
.TP
.B Email im mbox-Format:
.br
Die Mailbox liegt nach der Migration in $HOME/old-data/mail/loginname
.br
Windows-Daten werden nach $HOME/old_data/windows kopiert.
.br
Todo: Mail in den IMAP-Server kopieren.
.TP
.B Klassennamen:
.br
Achtung: Beim update von 2.x auf 3.x wird aus k7a die Klasse 7a.
.TP
.B Todo: Rembo/myshn 
.br
Achtung: Beim update von 2.x auf 3.x wird aus k7a die Klasse 7a.
.br
.SH WELCHE DATEN WERDEN NICHT ÜBERNOMMEN?
.TP
.B User, die nicht mehr in schueler.txt bzw. lehrer.txt sind. 
.br
Also user, die toleriert oder deaktiviert sind. Damit werden auch
deren Daten NICHT übernommen.
.TP
.B Veränderte Passwörter:
.br 
Jeder Benutzer bekommt wieder sein Erstpasswort (so wie auf den
Anmeldungskärtchen ausgedruckt). Veränderte Passwörter werden NICHT
übernommen.
.br
.SH DESCRIPTION
.B sophomorix-vampire  
wird auf einem neuen Server gestartet und holt dann Benutzer und und
Daten eines alten Servers.
.br

.TP
.B Step 1: --key --server 10.1.x.y
.br
Erzeugen eins passwortlosen ssh-keys und ablegen auf dem alten Server mit der IP 10.1.x.y. Oligatorisch, wenn von einem anderen Rechner migriert wird.
.br
Um den ssh-key auf dem alten Server ablegen zu können, muss dort ein
ssh login als root möglich sein. Falls sie das rootlogin abgeschaltet
haben, sollten sie es in /etc/ssh/sshd_config mit

PermitRootLogin yes

für die Migration wieder einschalten.
 
.TP
oder:
.TP
.B Todo Step 1: --localdisk  rootdir
.br
Holen der Daten von einer gemounteten Wechselplatte
.TP
.B Step 2: --fetch-files
.br
Konfigurationsdateien vom alten Server holen (nach root/sophomorix-vampire)
.TP
.B Step 3: --install-files
.br
Konfigurationsdateien von sophomorix patchen und ins neue System kopieren
.TP
.B Step 4: --sync-dirs
.br
Einige Verzeichnisse auf den neuen Server kopieren
.TP
.B Step 5: --sync-users
.br
Benutzer mit gleichen Loginnamen anlegen (numerische user id kann sich ändern). 
.TP
.B Step 6. Quota anpassen (Todo)
.br
Leider können die Quotawerte NICHT automatisch sinnvoll übernommen
werden. Deshalb sollte sie JETZT, bovor sie die Userdaten holen, die
Quota auf das neue System anpassen.
.TP
.B Step 7: --sync-homes
.br
Daten im Home der Benutzer abgleichen, user für user. Das kann dauern.
.TP
.B Step 8: --sync-workstations
.br
.B Todo: Workstation-accounts anlegen.
.TP
.B Step 9: --sync-shares
.br
.B  Synchronisieren der Klassentausch-Verzeichnisse aller Klassen des neuen Servers
.TP 
.TP
.B Step 10:
.br
.B Todo: Synchronisieren sonstiger Verzeichnisse
   (--rembo) rembo images synchronisieren
   (--mlscripten) 
   (--myshn)
   (--sync-network-shares)
.TP 
.PP
.SH OPTIONS
.B sophomorix-vampire
benützt die GNU command line syntax, mit langen Optionen, die mit zwei
Bindestrichen (`-') beginnen:
.TP
.B -h, --help
Kurzübersicht über Optionen, sowie eine Liste der eingelesenen Dateien.
.TP
.B -v, --verbose
Sagt, was das Programm gerade macht (verbose)
.TP
.B -vv, --verbose --verbose
Sagt ungeheuer genau, was das Programm gerade macht (very verbose)
.TP
.B --server ip, --server name
gibt an von welchem Server die Daten geholt werden sollen. Wenn die Namensauflösung funktioniert kann auch der name des servers benutzt werden.
.TP
.B --clear
löscht das Verzeichnis /root/sophomorix-vampire in dem Konfigurationsdateien des alten Servers liegen.
.TP
.SH SEE ALSO
.BR sophomorix (8),
.BR sophomorix-teach-in (8),
.BR sophomorix-add (8),
.BR sophomorix-move (8),
.BR sophomorix-print (8),
.BR sophomorix-kill (8),
.BR sophomorix-split (8),
.BR sophomorix-project (8),

.\".BR baz (1).
.\".br
.\"You can see the full options of the Programs by calling for example 
.\".IR "sophomrix-vampire -h" ,
.
.SH AUTHOR
This manual page was written by <jeffbeck@web.de>.
