#!/usr/bin/perl -w
# Dieses Script (sophomorix-test) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de


# weiter:

#Auswertung .add, .move, .kill


# Bibliotheken

use strict;
use Getopt::Long;
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
use Sophomorix::SophomorixFiles;
use Sophomorix::SophomorixTest;
use Test::More "no_plan";
Getopt::Long::Configure ("bundling");

# Einlesen der Konfigurationsdatei für Entwickler
#{ package DevelConf ; do "/etc/sophomorix/devel/user/sophomorix-devel.conf"}


system("install -d /root/sophomorix-test");

############################################################
# Start
############################################################

my $today=`date +%d.%m.%Y`;
print "\nToday is $today\n";
chomp($today);
my $verbose=0;

&run_command("sophomorix-check",$verbose);

print "\nDie Tests können beginnen\n\n";


print '
###########################################################################
#                                                                         #
#                           ANLEGEN VON SCHÜLERN                          #
#                                                                         #
###########################################################################
';

###########################################################################
# user in schueler.txt hinzufügen
my $user="";
my $login="";
my @users_to_add=(
     "",
     "m4kb;Maier;Jörg;12.10.1982;",
     "7A;Öztürk;Mohammed;2.4.82;",
     "2C;Wall;Larry;2.4.72;",
     "m1kb;M\203hn;\223liver;12.10.1982;",
   );


foreach $user (@users_to_add){
   &append_line("$user","${DevelConf::users_pfad}/schueler.txt");
}


###########################################################################
# Check
print "Adding $#users_to_add users to schueler.txt\n";
&run_command("sophomorix-check",$verbose);




###########################################################################
# Ergebnisdateien pruefen
# Test
&check_line_in_file(
  "m4kb::maier;joerg;12.10.1982::[-a-z]{2,}::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");
# Test
&check_line_in_file(
  "7a::oeztuerk;mohammed;02.04.1982::[-a-z]{2,}::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");
# Test
&check_line_in_file(
  "2c::wall;larry;02.04.1972::[-a-z]{2,}::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");
# Test
&check_line_in_file(
  "m1kb::mahn;oliver;12.10.1982::[-a-z]{2,}::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");


# Test
&check_emptyness("sophomorix.move");
# Test
&check_emptyness("sophomorix.kill");


###########################################################################
# user anlegen
&run_command("sophomorix-add",$verbose);


###########################################################################
# Ergebnisdateien prüfen
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
&check_emptyness("sophomorix.kill");



###########################################################################
# Druckdaten prüfen
# add.tex
&check_existence("${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("joerg maier",
                    "${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("mohammed oeztuerk",
                    "${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("larry wall",
                    "${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("oliver mahn",
                    "${DevelConf::druck_pfad}/add.tex");
# andere
&check_existence("${DevelConf::druck_pfad}/add.dvi");
&check_existence("${DevelConf::druck_pfad}/add.ps");
&check_existence("${DevelConf::druck_pfad}/add.pdf");



###########################################################################
# Datenbank prüfen
&check_line_in_file(":joerg maier:","/etc/passwd");
&check_line_in_file(
  "m4kb;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982",
  "$DevelConf::protokoll_pfad/user_db");

&check_line_in_file(":mohammed oeztuerk:","/etc/passwd");
&check_line_in_file(
  "7a;mohammed oeztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982",
  "$DevelConf::protokoll_pfad/user_db");

&check_line_in_file(":larry wall:","/etc/passwd");
&check_line_in_file(
  "2c;larry wall;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1972",
  "$DevelConf::protokoll_pfad/user_db");

&check_line_in_file(":oliver mahn:","/etc/passwd");
&check_line_in_file(
  "m1kb;oliver mahn;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982",
  "$DevelConf::protokoll_pfad/user_db");



print '
###########################################################################
#                                                                         #
#                SCHÜLER DULDEN, DEAKTIVIEREN, LOESCHEN                   #
#                                                                         #
###########################################################################
';

&remove_line(
  "m4kb;Maier;Jörg;12.10.1982;",
  "${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
&check_emptyness("sophomorix.kill");

# Is toleration set
&check_line_in_file(":joerg maier:","/etc/passwd");
&check_line_in_file(
  "m4kb;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982;[A-Za-z0-9]*;[A-D]?;T;$today;[\.0-9]*;[a-z0-9]*;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");


$login=&get_login_name("m4kb;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982");

# make user tolerated for a looooong time
&update_user_db_entry($login,"TolerationDate=01.01.1970");
# check if this was succesful
&check_line_in_file(
  "m4kb;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982;[A-Za-z0-9]*;[A-D]?;T;01.01.1970;[\.0-9]*;[a-z0-9]*;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");

&run_command("sophomorix-check",$verbose);

# Test if user is moveable to dachboden
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.kill");
$login=&get_login_name("m4kb;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982");
&check_line_in_file(
  "${login}::m4kb::dachboden",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");

&run_command("sophomorix-move",$verbose);

# check if user has deactivated settings in user_db
# and ExitAdminClass is correct
&check_line_in_file(
  "dachboden;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982;[A-Za-z0-9]*;[A-D]?;D;01.01.1970;$today;m4kb;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");


$login=&get_login_name("dachboden;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982");
&check_account($login,"disabled");

&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.kill");
&check_emptyness("sophomorix.move");


# make user deactivated for a looooong time
&update_user_db_entry($login,"DeactivationDate=01.01.1971");
# check if this was succesful
&check_line_in_file(
  "dachboden;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982;[A-Za-z0-9]*;[A-D]?;D;01.01.1970;01.01.1971;m4kb;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");

$login=&get_login_name("dachboden;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982");

&run_command("sophomorix-check",$verbose);

&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");

&check_line_in_file(
  "maier;joerg;12.10.1982::${login}",
  "${DevelConf::ergebnis_pfad}/sophomorix.kill");


&run_command("sophomorix-kill",$verbose);

&check_account($login,"nonexisting");




print '
###########################################################################
#                                                                         #
#                SCHÜLER DULDEN - DANN KOMMT ER WIEDER                    #
#                        ======                                           #
###########################################################################
';

&remove_line(
  "7A;Öztürk;Mohammed;2.4.82;",
  "${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");

# ??? weshalb sollt move leer sein, kommt doch in den dachboden
# Warum ist der Test trotzdem OK???
#&check_emptyness("sophomorix.move");

$login=&get_login_name("7a;mohammed oeztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982.*");

&check_line_in_file(
  "${login}::7a::dachboden",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");


&check_emptyness("sophomorix.kill");

# Is toleration set
&check_line_in_file(":mohammed oeztuerk:","/etc/passwd");
&check_line_in_file(
  "7a;mohammed oeztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982;[A-Za-z0-9]*;[A-D]?;T;$today;[\.0-9]*;[a-z0-9]*;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");

# The users shows up again in schueler.txt in a different class
&append_line("7C;Öztürk;Mohammed;2.4.82;","${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.kill");


$login=&get_login_name("7a;mohammed oeztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982.*");

&check_line_in_file(
  "${login}::7a::7c",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");


&check_line_in_file(
  "7a;mohammed oeztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982;[A-Za-z0-9]*;[A-D]?;E;;;",
  "$DevelConf::protokoll_pfad/user_db");

&run_command("sophomorix-move",$verbose);


&check_line_in_file(
  "7c;mohammed oeztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982;[A-Za-z0-9]*;[A-D]?;E;;;[a-z0-9]*;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");

$login=&get_login_name("7c;mohammed oeztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982.*");

&check_account($login,"enabled");


print '
###########################################################################
#                                                                         #
#             SCHÜLER DEAKTIVIEREN - DANN KOMMT ER WIEDER                 #
#                     ============                                        #
###########################################################################
';

&remove_line(
  "2C;Wall;Larry;2.4.72;",
  "${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);
#&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.kill");

$login=&get_login_name("2c;larry wall;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1972*");
&check_line_in_file(
  "${login}::2c::dachboden",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");

&run_command("sophomorix-move",$verbose);

$login=&get_login_name("dachboden;larry wall;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1972;[A-Za-z0-9]*;[A-D]?;T;$today;;2c;[A-Z]*;");

# make user tolerated for a looooong time
&update_user_db_entry($login,"TolerationDate=01.01.1970");

&run_command("sophomorix-check",$verbose);

# user should be deactivated now

$login=&get_login_name("dachboden;larry wall;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1972");
&check_account($login,"disabled");


# The users shows up again in schueler.txt in a different class
&append_line("3C;Wall;Larry;2.4.72;","${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.kill");

$login=&get_login_name("dachboden;larry wall;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1972");


&check_line_in_file(
  "${login}::dachboden::3c",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");

&run_command("sophomorix-move",$verbose);



&check_line_in_file(
  "3c;larry wall;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1972;[A-Za-z0-9]*;[A-D]?;E;;;2c;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");

$login=&get_login_name("3c;larry wall;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1972.*");
&check_account($login,"enabled");


print '
###########################################################################
#                                                                         #
#                              AUTO-TEACH-IN TESTEN                       #
#                                                                         #
###########################################################################
';

# updating the name Öz -> Ötz
&exchange_line_in_file("7C;Öztürk;Mohammed;2.4.82;*",
   "/etc/sophomorix/user/schueler.txt",
   "7C;Ötztürk;Mohammed;2.4.82;");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
&check_emptyness("sophomorix.kill");


&check_line_in_file(
  "7c;mohammed oetztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982;[A-Za-z0-9]*;[A-D]?;E;;;[a-z0-9]*;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");

# updating the first Mohhammed -> Mohammad
&exchange_line_in_file("7C;Ötztürk;Mohammed;2.4.82;*",
   "/etc/sophomorix/user/schueler.txt",
   "7C;Ötztürk;Mohammad;2.4.82;");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
&check_emptyness("sophomorix.kill");


&check_line_in_file(
  "7c;mohammad oetztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982;[A-Za-z0-9]*;[A-D]?;E;;;[a-z0-9]*;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");


# updating birth 82 -> 83
&exchange_line_in_file("7C;Ötztürk;Mohammad;2.4.82;*",
   "/etc/sophomorix/user/schueler.txt",
   "7C;Ötztürk;Mohammad;2.4.83;");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
&check_emptyness("sophomorix.kill");


&check_line_in_file(
  "7c;mohammad oetztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1983;[A-Za-z0-9]*;[A-D]?;E;;;[a-z0-9]*;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");




print '
###########################################################################
#                                                                         #
#                      UNID HOCHLADEN - DATEN ÄNDERN                      #
#                                                                         #
###########################################################################
';

# updating the unid
&exchange_line_in_file("3C;Wall;Larry;2.4.72;*",
   "/etc/sophomorix/user/schueler.txt",
   "3C;Wall;Larry;2.4.72;123456789;");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
&check_emptyness("sophomorix.kill");


&check_line_in_file(
  "3c;larry wall;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1972;123456789;[A-D]?;E;;;[a-z0-9]*;[A-Z]*;",
  "$DevelConf::protokoll_pfad/user_db");

# new name, first, birth
&exchange_line_in_file("3C;Wall;Larry;2.4.72;*",
   "/etc/sophomorix/user/schueler.txt",
   "3C;Stallman;Richard;2.4.62;123456789;");


&run_command("sophomorix-check",$verbose);



print '
###########################################################################
# # # NOCH ANGELEGTE USER ENTFERNEN # # #
###########################################################################
';


&remove_line(
  "7C;Ötztürk;Mohammad;2.4.83;",
  "${DevelConf::users_pfad}/schueler.txt");
#&remove_line(
#  "3C;Wall;Larry;2.4.72;",
#  "${DevelConf::users_pfad}/schueler.txt");
&remove_line(
  "3C;Stallman;Richard;2.4.62;",
  "${DevelConf::users_pfad}/schueler.txt");
&remove_line(
  "m1kb;M\203hn;\223liver;12.10.1982;",
  "${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);

$login=&get_login_name("7c;mohammad oetztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1983");
# make user tolerated for a looooong time
&update_user_db_entry($login,"TolerationDate=01.01.1970");

$login=&get_login_name("3c;richard stallman;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1962");
# make user tolerated for a looooong time
&update_user_db_entry($login,"TolerationDate=01.01.1970");

$login=&get_login_name("m1kb;oliver mahn;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982");
# make user tolerated for a looooong time
&update_user_db_entry($login,"TolerationDate=01.01.1970");


&run_command("sophomorix-check",$verbose);

&run_command("sophomorix-move",$verbose);

my @logins=();


$login=&get_login_name("dachboden;mohammad oetztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1983");

push @logins, $login;

&check_account($login,"disabled");
&update_user_db_entry($login,"DeactivationDate=01.01.1971");


$login=&get_login_name("dachboden;richard stallman;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1962");
push @logins, $login;
&check_account($login,"disabled");
&update_user_db_entry($login,"DeactivationDate=01.01.1971");

$login=&get_login_name("dachboden;oliver mahn;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982");
push @logins, $login;
&check_account($login,"disabled");
&update_user_db_entry($login,"DeactivationDate=01.01.1971");

&run_command("sophomorix-check",$verbose);


&run_command("sophomorix-kill",$verbose);


foreach my $login (@logins){
   &check_account($login,"nonexisting");
}


exit;

###########################################################################
# END OF TESTS
###########################################################################



###########################################################################
# User mit Gewalt entfernen
# Nicht Teil des Tests

$login=&remove_line(
  "m4kb;joerg maier;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982",
  "$DevelConf::protokoll_pfad/user_db");
&remove_line(
  "m4kb;Maier;Jörg;12.10.1982;",
  "${DevelConf::users_pfad}/schueler.txt");
&kill_user("$login");

$login=&remove_line(
  "7a;mohammed oeztuerk;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1982",
  "$DevelConf::protokoll_pfad/user_db");
&remove_line(
  "7A;Öztürk;Mohammed;2.4.82;",
  "${DevelConf::users_pfad}/schueler.txt");
&kill_user("$login");

$login=&remove_line(
  "m1kb;oliver mahn;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982",
  "$DevelConf::protokoll_pfad/user_db");
&remove_line(
  "m1kb;M\203hn;\223liver;12.10.1982;",
  "${DevelConf::users_pfad}/schueler.txt");
&kill_user("$login");




&exchange_line_in_file("fdgdtzz",
   "/etc/sophomorix/user/schueler.txt",
   "13a;Maier;Jörg;12.10.1982;");














