#!/usr/bin/perl -w
# $Id$
# Dieses Script (sophomorix-test) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de


# weiter:

#Auswertung .add, .move, .kill


# Bibliotheken

use strict;
use Getopt::Long;
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
#use Sophomorix::SophomorixFiles;
use Sophomorix::SophomorixPgLdap;
use Sophomorix::SophomorixTest;
use Test::More "no_plan";
Getopt::Long::Configure ("bundling");

use DBI;
use Net::LDAP;

my @arguments = @ARGV;

system("install -d /root/sophomorix-test");

############################################################
# Start
############################################################
&check_connections();
&log_script_start(@arguments);


my $server="server";
my $win_magic="2147483647";

# sid
my $sid_string=`net getlocalsid`;
chomp($sid_string);
my ($rubbish,$sid) = split(/: /,$sid_string);

my $usid;
my $gsid;


my $today=`date +%d.%m.%Y`;
my $today_pg=`date +%Y-%m-%d`;
chomp($today);
chomp($today_pg);

print "\nToday is $today (pg: $today_pg)\n";
my $verbose=0;

my %account=();


&run_command("sophomorix-check",$verbose);

print '
###########################################################################
#                                                                         #
#                                ADDING USERS                             #
#                                                                         #
###########################################################################
';

###########################################################################
# user in schueler.txt hinzufügen
my $user="";
my $login="";
my @users_to_add=(
     "",
     "m4kb;Maier;Jörg;12.10.1982;",
     "7A;Öztürk;Mohammed;2.4.82;",
     "2C;Wall;Larry;2.4.72;",
     "m1kb;M\203hn;\223liver;12.10.1982;987654321;",
   );


my @teachers_to_add=(
     "",
     "lehrer;Darwin;Charles;12.10.1942;darwin;",
   );


foreach my $user (@users_to_add){
   &append_line("$user","${DevelConf::users_pfad}/schueler.txt");
}

foreach my $teacher (@teachers_to_add){
   &append_line("$teacher","${DevelConf::users_pfad}/lehrer.txt");
}


###########################################################################
# Check
print "   *** Adding $#users_to_add users to schueler.txt\n";
&run_command("sophomorix-check",$verbose);




###########################################################################
# Ergebnisdateien pruefen
# Test
&check_line_in_file(
  "m4kb::Maier;Jörg;12.10.1982::[-a-z]{2,}::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");
# Test
&check_line_in_file(
  "7a::Öztürk;Mohammed;02.04.1982::[-a-z]{2,}::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");
# Test
&check_line_in_file(
  "2c::Wall;Larry;02.04.1972::[-a-z]{2,}::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");
# Test
&check_line_in_file(
  "m1kb::Mahn;oliver;12.10.1982::[-a-z]{2,}::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");
# Test
&check_line_in_file(
  "teachers::Darwin;Charles;12.10.1942::darwin::[-a-z]{3,}",
  "${DevelConf::ergebnis_pfad}/sophomorix.add");

# Test
&check_emptyness("sophomorix.move");
# Test
&check_emptyness("sophomorix.kill");


###########################################################################
# user anlegen
&run_command("sophomorix-add",$verbose);

# doppelt, wegen bug
&run_command("sophomorix-add",$verbose);


###########################################################################
# Ergebnisdateien prüfen
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
&check_emptyness("sophomorix.kill");



###########################################################################
# Druckdaten prüfen
# add.tex
&check_existence("${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("Jörg Maier",
                    "${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("Mohammed Öztürk",
                    "${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("Larry Wall",
                    "${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("oliver Mahn",
                    "${DevelConf::druck_pfad}/add.tex");
&check_line_in_file("Charles Darwin",
                    "${DevelConf::druck_pfad}/add.tex");

# andere
&check_existence("${DevelConf::druck_pfad}/add.dvi");
&check_existence("${DevelConf::druck_pfad}/add.ps");
&check_existence("${DevelConf::druck_pfad}/add.pdf");



###########################################################################
# Datenbank prüfen


%account = &fetch_single_account("surname='Maier' 
                                  AND firstname='Jörg'
                                  AND birthday='1982-10-12'
                                  AND adminclass='m4kb'",
                      );
&ok_account("sophomorixstatus", "U");
&ok_account("creationdate", $today_pg);
&ok_account("gecos", "Jörg Maier");
&ok_account("gid", "m4kb");
&ok_account("homedirectory", "/home/students/m4kb/$account{'uid'}");
# samba
&ok_account("displayname", "Jörg Maier");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");

&check_provided_files($account{ 'uid' },"m4kb");
&check_groups($account{ 'uid' },"m4kb");




%account = &fetch_single_account("surname='Öztürk' 
                                  AND firstname='Mohammed'
                                  AND birthday='1982-04-02'
                                  AND adminclass='7a'",
                      );
&ok_account("sophomorixstatus", "U");
&ok_account("creationdate", $today_pg);
&ok_account("gecos", "Mohammed Öztürk");
&ok_account("gid", "7a");
&ok_account("homedirectory", "/home/students/7a/$account{'uid'}");
# samba
&ok_account("displayname", "Mohammed Öztürk");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");

&check_provided_files($account{ 'uid' },"7a");
&check_groups($account{ 'uid' },"7a");



%account = &fetch_single_account("surname='Wall' 
                                  AND firstname='Larry'
                                  AND birthday='1972-04-02'
                                  AND adminclass='2c'",
                      );
&ok_account("sophomorixstatus", "U");
&ok_account("creationdate", $today_pg);
&ok_account("gecos", "Larry Wall");
&ok_account("gid", "2c");
&ok_account("homedirectory", "/home/students/2c/$account{'uid'}");
# samba
&ok_account("displayname", "Larry Wall");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");

&check_provided_files($account{ 'uid' },"2c");
&check_groups($account{ 'uid' },"2c");



%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1982-10-12'
                                  AND adminclass='m1kb'",
                      );
&ok_account("sophomorixstatus", "U");
&ok_account("creationdate", $today_pg);
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "987654321");
&ok_account("gid", "m1kb");
&ok_account("homedirectory", "/home/students/m1kb/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");

&check_provided_files($account{ 'uid' },"m1kb");
&check_groups($account{ 'uid' },"m1kb");


%account = &fetch_single_account("surname='Darwin' 
                                  AND firstname='Charles'
                                  AND birthday='1942-10-12'
                                  AND adminclass='teachers'",
                      );
&ok_account("sophomorixstatus", "U");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "");
&ok_account("deactivationdate", "");
&ok_account("gecos", "Charles Darwin");
&ok_account("unid", "");
&ok_account("exitunid", "");
&ok_account("gid", "teachers");
&ok_account("homedirectory", "/home/teachers/$account{'uid'}");
# samba
&ok_account("displayname", "Charles Darwin");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");

&check_provided_files($account{ 'uid' },"teachers");
&check_groups($account{ 'uid' },"teachers");



print '
###########################################################################
#                                                                         #
#                TOLERATE, DEACTIVATE AND DELETE USERS                    #
#                                                                         #
###########################################################################
';


&remove_line(
  "m4kb;Maier;Jörg;12.10.1982;",
  "${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);


# Is toleration set
%account = &fetch_single_account("surname='Maier' 
                                  AND firstname='Jörg'
                                  AND birthday='1982-10-12'
                                  AND adminclass='m4kb'",
                      );
&ok_account("sophomorixstatus", "T");
&ok_account("tolerationdate", $today_pg);
&ok_account("gecos", "Jörg Maier");
&ok_account("gid", "m4kb");
&ok_account("homedirectory", "/home/students/m4kb/$account{'uid'}");
# samba
&ok_account("displayname", "Jörg Maier");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# Test if user is moveable to dachboden
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.kill");
&check_line_in_file(
  "${login}::m4kb::dachboden",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");


# move user
&run_command("sophomorix-move",$verbose);

# check movement
%account = &fetch_single_account("surname='Maier' 
                                AND firstname='Jörg'
                                AND birthday='1982-10-12'
                                AND adminclass='dachboden'",
                              );
&ok_account("exitadminclass", "m4kb");
&ok_account("gecos", "Jörg Maier");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "Jörg Maier");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");




# Fetch login of user
$login = &fetch_login("surname='Maier' 
                       AND firstname='Jörg'
                       AND birthday='1982-10-12'
                       AND adminclass='dachboden'",
                     );


# make user tolerated for a looooong time
&update_user_db_entry($login,"TolerationDate=01.01.1970");
%account = &fetch_single_account("surname='Maier' 
                                  AND firstname='Jörg'
                                  AND birthday='1982-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "T");
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "");
&ok_account("gecos", "Jörg Maier");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "Jörg Maier");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");



&run_command("sophomorix-check",$verbose);



# Is deactivation set
%account = &fetch_single_account("surname='Maier' 
                                  AND firstname='Jörg'
                                  AND birthday='1982-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "D");
&ok_account("deactivationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("exitadminclass", "m4kb");
&ok_account("gecos", "Jörg Maier");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "Jörg Maier");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# todo ???????????????ßßß
#&check_account($login,"disabled");


# make user deactivated for a looooong time
&update_user_db_entry($login,"DeactivationDate=01.01.1971");

# check if this was succesful
%account = &fetch_single_account("surname='Maier' 
                                  AND firstname='Jörg'
                                  AND birthday='1982-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "D");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("exitadminclass", "m4kb");
&ok_account("gecos", "Jörg Maier");
&ok_account("unid", "");
&ok_account("exitunid", "");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "Jörg Maier");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


&run_command("sophomorix-check",$verbose);


&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");

&check_line_in_file(
  "Maier;Jörg;12.10.1982::${login}",
  "${DevelConf::ergebnis_pfad}/sophomorix.kill");



# todo ?????????????ß
#&run_command("sophomorix-kill",$verbose);

#&check_account($login,"nonexisting");




print '
###########################################################################
#                                                                         #
#                STUDENT IS TOLERATED - COMES BACK AGAIN                  #
#                           =========                                     #
###########################################################################
';

&remove_line(
  "7A;Öztürk;Mohammed;2.4.82;",
  "${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);



# Test
$login = &fetch_login("surname='Öztürk' 
                       AND firstname='Mohammed'
                       AND birthday='1982-04-02'
                       AND adminclass='7a'",
                     );
&check_emptyness("sophomorix.add");

# Fetch login of user
&check_line_in_file(
  "${login}::7a::dachboden",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");



# Is user tolerated?
%account = &fetch_single_account("surname='Öztürk' 
                                  AND firstname='Mohammed'
                                  AND birthday='1982-04-02'
                                  AND adminclass='7a'",
                      );
&ok_account("sophomorixstatus", "T");
&ok_account("tolerationdate", $today_pg);
&ok_account("gecos", "Mohammed Öztürk");
&ok_account("gid", "7a");
&ok_account("homedirectory", "/home/students/7a/$account{'uid'}");
# samba
&ok_account("displayname", "Mohammed Öztürk");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");




# The users shows up again in schueler.txt in a different class
&append_line("7C;Öztürk;Mohammed;2.4.82;","${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");

&check_line_in_file(
  "${login}::7a::7c",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");



# Reactivation OK?
%account = &fetch_single_account("surname='Öztürk' 
                                  AND firstname='Mohammed'
                                  AND birthday='1982-04-02'
                                  AND adminclass='7a'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("tolerationdate", "");
&ok_account("gecos", "Mohammed Öztürk");
&ok_account("gid", "7a");
&ok_account("homedirectory", "/home/students/7a/$account{'uid'}");
# samba
&ok_account("displayname", "Mohammed Öztürk");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


&run_command("sophomorix-move",$verbose);


# Move OK?
%account = &fetch_single_account("surname='Öztürk' 
                                  AND firstname='Mohammed'
                                  AND birthday='1982-04-02'
                                  AND adminclass='7c'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("tolerationdate", "");
&ok_account("gecos", "Mohammed Öztürk");
&ok_account("gid", "7c");
# samba
&ok_account("displayname", "Mohammed Öztürk");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");





# todo ???????????
#&check_account($login,"enabled");



print '
###########################################################################
#                                                                         #
#                  STUDENT IS DEACTIVATED - COMES BACK                    #
#                             ===========                                 #
###########################################################################
';

&remove_line(
  "2C;Wall;Larry;2.4.72;",
  "${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);
#&run_command("sophomorix-check",$verbose);



# Is user tolerated now? 
%account = &fetch_single_account("surname='Wall' 
                                  AND firstname='Larry'
                                  AND birthday='1972-04-02'
                                  AND adminclass='2c'",
                      );
&ok_account("sophomorixstatus", "T");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", $today_pg);
&ok_account("gecos", "Larry Wall");
&ok_account("gid", "2c");
&ok_account("homedirectory", "/home/students/2c/$account{'uid'}");
# samba
&ok_account("displayname", "Larry Wall");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");



# Test
$login = &fetch_login("surname='Wall' 
                       AND firstname='Larry'
                       AND birthday='1972-04-02'
                       AND adminclass='2c'",
                     );
&check_emptyness("sophomorix.add");
#&check_emptyness("sophomorix.kill");
&check_line_in_file(
  "${login}::2c::dachboden",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");



&run_command("sophomorix-move",$verbose);


# make user tolerated for a looooong time
&update_user_db_entry($login,"TolerationDate=01.01.1970");

&run_command("sophomorix-check",$verbose);


# Is user deactivated now? 
%account = &fetch_single_account("surname='Wall' 
                                  AND firstname='Larry'
                                  AND birthday='1972-04-02'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "D");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", $today_pg);
&ok_account("gecos", "Larry Wall");
&ok_account("exitadminclass", "2c");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "Larry Wall");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");





# todo ????????
#&check_account($login,"disabled");


# The users shows up again in schueler.txt in a different class
&append_line("3C;Wall;Larry;2.4.72;","${DevelConf::users_pfad}/schueler.txt");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
#&check_emptyness("sophomorix.kill");

&check_line_in_file(
  "${login}::dachboden::3c",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");

&run_command("sophomorix-move",$verbose);


# Is user Moved and Enabled
%account = &fetch_single_account("surname='Wall' 
                                  AND firstname='Larry'
                                  AND birthday='1972-04-02'
                                  AND adminclass='3c'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("creationdate", $today_pg);
&ok_account("exitadminclass", "2c");
&ok_account("creationdate", $today_pg);
&ok_account("gecos", "Larry Wall");
&ok_account("gid", "3c");
&ok_account("homedirectory", "/home/students/3c/$account{'uid'}");
# samba
&ok_account("displayname", "Larry Wall");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# todo ????????ß
#&check_account($login,"enabled");


print '
###########################################################################
#                                                                         #
#                    TESTING  AUTO-TEACH-IN OF STUDENTS                   #
#                                                                         #
###########################################################################
';

# updating the name Öz -> Ötz
&exchange_line_in_file("7C;Öztürk;Mohammed;2.4.82;*",
   "/etc/sophomorix/user/schueler.txt",
   "7C;Ötztürk;Mohammed;2.4.82;");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
#&check_emptyness("sophomorix.kill");

%account = &fetch_single_account("surname='Ötztürk' 
                                  AND firstname='Mohammed'
                                  AND birthday='1982-04-02'
                                  AND adminclass='7c'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("gecos", "Mohammed Ötztürk");
&ok_account("gid", "7c");
&ok_account("homedirectory", "/home/students/7c/$account{'uid'}");
# samba
&ok_account("displayname", "Mohammed Ötztürk");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# updating the first Mohhammed -> Mohammad
&exchange_line_in_file("7C;Ötztürk;Mohammed;2.4.82;*",
   "/etc/sophomorix/user/schueler.txt",
   "7C;Ötztürk;Mohammad;2.4.82;");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
#&check_emptyness("sophomorix.kill");



%account = &fetch_single_account("surname='Ötztürk' 
                                  AND firstname='Mohammad'
                                  AND birthday='1982-04-02'
                                  AND adminclass='7c'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("gecos", "Mohammad Ötztürk");
&ok_account("gid", "7c");
&ok_account("homedirectory", "/home/students/7c/$account{'uid'}");
# samba
&ok_account("displayname", "Mohammad Ötztürk");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# updating birth 82 -> 83
&exchange_line_in_file("7C;Ötztürk;Mohammad;2.4.82;*",
   "/etc/sophomorix/user/schueler.txt",
   "7C;Ötztürk;Mohammad;2.4.83;");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
#&check_emptyness("sophomorix.kill");

%account = &fetch_single_account("surname='Ötztürk' 
                                  AND firstname='Mohammad'
                                  AND birthday='1983-04-02'
                                  AND adminclass='7c'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("gecos", "Mohammad Ötztürk");
&ok_account("gid", "7c");
&ok_account("homedirectory", "/home/students/7c/$account{'uid'}");
# samba
&ok_account("displayname", "Mohammad Ötztürk");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");




print '
###########################################################################
#                                                                         #
#              TESTING UPLOADING UNID, CHANGE DATA USING UNID             #
#                                                                         #
###########################################################################
';

# updating the unid automatically
&exchange_line_in_file("3C;Wall;Larry;2.4.72;*",
   "/etc/sophomorix/user/schueler.txt",
   "3C;Wall;Larry;2.4.72;123456789;");

&run_command("sophomorix-check",$verbose);

# Test
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
#&check_emptyness("sophomorix.kill");

%account = &fetch_single_account("surname='Wall' 
                                  AND firstname='Larry'
                                  AND birthday='1972-04-02'
                                  AND adminclass='3c'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("creationdate", $today_pg);
&ok_account("gecos", "Larry Wall");
&ok_account("unid", "123456789");
&ok_account("gid", "3c");
&ok_account("homedirectory", "/home/students/3c/$account{'uid'}");
# samba
&ok_account("displayname", "Larry Wall");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# new name, first, birth
&exchange_line_in_file("3C;Wall;Larry;2.4.72;*",
   "/etc/sophomorix/user/schueler.txt",
   "3C;Stallman;Richard;2.4.62;123456789;");


&run_command("sophomorix-check",$verbose);



%account = &fetch_single_account("surname='Stallman' 
                                  AND firstname='Richard'
                                  AND birthday='1962-04-02'
                                  AND adminclass='3c'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("creationdate", $today_pg);
&ok_account("gecos", "Richard Stallman");
&ok_account("unid", "123456789");
&ok_account("gid", "3c");
&ok_account("homedirectory", "/home/students/3c/$account{'uid'}");
# samba
&ok_account("displayname", "Richard Stallman");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");




print '
###########################################################################
#                                                                         #
#                               DELETE UNID                               #
#                                                                         #
###########################################################################
';

# removing the whole line should delete UNID
&remove_line(
  "m1kb;M\203hn;\223liver;12.10.1982;",
  "${DevelConf::users_pfad}/schueler.txt");


&run_command("sophomorix-check",$verbose);



# check if user is tolerated and unid is removed
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1982-10-12'
                                  AND adminclass='m1kb'",
                      );
&ok_account("sophomorixstatus", "T");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", $today_pg);
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "m1kb");
&ok_account("homedirectory", "/home/students/m1kb/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[UX]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# User comes back with correction (Birthday), but same unid as in system
&append_line("m1kb;M\203hn;\223liver;12.10.1984;987654321;",
              "${DevelConf::users_pfad}/schueler.txt");


&run_command("sophomorix-check",$verbose);



# check if data is uploaded
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='m1kb'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "987654321");
&ok_account("exitunid", "987654321");
&ok_account("gid", "m1kb");
&ok_account("homedirectory", "/home/students/m1kb/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");





# removing the unid from userfile
&exchange_line_in_file("m1kb;M\203hn;\223liver;12.10.1984;987654321;",
   "/etc/sophomorix/user/schueler.txt",
   "m1kb;M\203hn;\223liver;12.10.1984;");



&run_command("sophomorix-check",$verbose);


# check if unid is removed
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='m1kb'",
                      );
&ok_account("sophomorixstatus", "E");
&ok_account("creationdate", $today_pg);
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("gid", "m1kb");
&ok_account("homedirectory", "/home/students/m1kb/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");






print '
###########################################################################
#                                                                         #
#                   MAKE ALL USERS REMOVEABLE                             #
#                                                                         #
###########################################################################
';

# remove the lines
&remove_line(
  "7C;Ötztürk;Mohammad;2.4.83;",
  "${DevelConf::users_pfad}/schueler.txt");
&remove_line(
  "3C;Stallman;Richard;2.4.62;",
  "${DevelConf::users_pfad}/schueler.txt");
&remove_line(
  "m1kb;M\203hn;\223liver;12.10.1984;",
  "${DevelConf::users_pfad}/schueler.txt");

&remove_line(
  "lehrer\\s*;Darwin\\s*;Charles\\s*;12.10.1942.*",
  "${DevelConf::users_pfad}/lehrer.txt");


&run_command("sophomorix-check",$verbose);


# colecting all logins
my @logins=();

$login = &fetch_login("surname='Ötztürk' 
                       AND firstname='Mohammad'
                       AND birthday='1983-04-02'
                       AND adminclass='7c'",
                     );
push @logins, $login;

$login = &fetch_login("surname='Stallman' 
                       AND firstname='Richard'
                       AND birthday='1962-04-02'
                       AND adminclass='3c'",
                     );
push @logins, $login;

$login = &fetch_login("surname='Mahn' 
                       AND firstname='oliver'
                       AND birthday='1984-10-12'
                       AND adminclass='m1kb'",
                     );
push @logins, $login;

$login = &fetch_login("surname='Darwin' 
                       AND firstname='Charles'
                       AND birthday='1942-10-12'
                       AND adminclass='teachers'",
                     );
push @logins, $login;




# make user tolerated for a looooong time
foreach my $login (@logins){
    &update_user_db_entry($login,"TolerationDate=01.01.1970");
}



&run_command("sophomorix-check",$verbose);
&run_command("sophomorix-move",$verbose);


foreach my $login (@logins){
   # todo ???????
   #&check_account($login,"disabled");
}


# make user deactivated for a looooong time
foreach my $login (@logins){
   &update_user_db_entry($login,"DeactivationDate=01.01.1971");
}


&run_command("sophomorix-check",$verbose);



# check if users are removeable (R)
%account = &fetch_single_account("surname='Maier' 
                                  AND firstname='Jörg'
                                  AND birthday='1982-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "R");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("exitadminclass", "m4kb");
&ok_account("gecos", "Jörg Maier");
&ok_account("unid", "");
&ok_account("exitunid", "");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "Jörg Maier");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


%account = &fetch_single_account("surname='Ötztürk' 
                                  AND firstname='Mohammad'
                                  AND birthday='1983-04-02'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "R");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "Mohammad Ötztürk");
&ok_account("unid", "");
&ok_account("exitunid", "");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "Mohammad Ötztürk");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


%account = &fetch_single_account("surname='Stallman' 
                                  AND firstname='Richard'
                                  AND birthday='1962-04-02'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "R");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "Richard Stallman");
&ok_account("unid", "");
&ok_account("exitunid", "123456789");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "Richard Stallman");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# 
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "R");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


%account = &fetch_single_account("surname='Darwin' 
                                  AND firstname='Charles'
                                  AND birthday='1942-10-12'
                                  AND adminclass='speicher'",
                      );
&ok_account("sophomorixstatus", "R");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "Charles Darwin");
&ok_account("unid", "");
&ok_account("exitunid", "");
&ok_account("gid", "speicher");
&ok_account("homedirectory", "/home/students/speicher/$account{'uid'}");
# samba
&ok_account("displayname", "Charles Darwin");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");



print '
###########################################################################
#                                                                         #
#                     MANUALLY CHANGE USERSTATUS                          #
#                                                                         #
###########################################################################
';

# user the user Mahn
$login = &fetch_login("surname='Mahn' 
                       AND firstname='oliver'
                       AND birthday='1984-10-12'
                       AND adminclass='dachboden'",
                     );


# Make the account Permanent
&run_command("sophomorix-user -P $login",$verbose);


# check if permanent 
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "P");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");

# todo?????? check_account

# Make the account Killable
&run_command("sophomorix-user -K $login",$verbose);


#?????

# check if Killable 
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "K");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");

# This should not change anything
&run_command("sophomorix-check",$verbose);

# Ergebnisdateien prüfen
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
#&check_emptyness("sophomorix.kill");



# check if still Killable 
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "K");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# Make the account Freeze
&run_command("sophomorix-user -F $login",$verbose);


# check if Frozen 
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "F");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");

# This should not change anything
&run_command("sophomorix-check",$verbose);


# Ergebnisdateien prüfen
&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");
#&check_emptyness("sophomorix.kill");


# check if still Frozen
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "F");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "1970-01-01");
&ok_account("deactivationdate", "1971-01-01");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[DU]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");



# Activate the Account
&run_command("sophomorix-user -A $login",$verbose);


# check 
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='dachboden'",
                      );
&ok_account("sophomorixstatus", "A");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "$today_pg");
&ok_account("deactivationdate", "");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "dachboden");
&ok_account("homedirectory", "/home/students/dachboden/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# Check if the account can be moved to exitadminclass
&run_command("sophomorix-check",$verbose);

# Ergebnisdateien prüfen
&check_emptyness("sophomorix.add");
#&check_emptyness("sophomorix.kill");

&check_line_in_file(
  "${login}::dachboden::m1kb",
  "${DevelConf::ergebnis_pfad}/sophomorix.move");


# Move the account
&run_command("sophomorix-move",$verbose);


# check movement and activation 
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='m1kb'",
                      );
&ok_account("sophomorixstatus", "A");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "");
&ok_account("deactivationdate", "");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "m1kb");
&ok_account("homedirectory", "/home/students/m1kb/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");


# since it was manually activated it should not be moved


# Check if the account can be moved to exitadminclass
&run_command("sophomorix-check ",$verbose);


&check_emptyness("sophomorix.add");
&check_emptyness("sophomorix.move");


# Move the account
&run_command("sophomorix-move",$verbose);


# check that account stays activated and was NOT moved to dachboden
%account = &fetch_single_account("surname='Mahn' 
                                  AND firstname='oliver'
                                  AND birthday='1984-10-12'
                                  AND adminclass='m1kb'",
                      );
&ok_account("sophomorixstatus", "A");
&ok_account("creationdate", $today_pg);
&ok_account("tolerationdate", "");
&ok_account("deactivationdate", "");
&ok_account("gecos", "oliver Mahn");
&ok_account("unid", "");
&ok_account("exitunid", "987654321");
&ok_account("gid", "m1kb");
&ok_account("homedirectory", "/home/students/m1kb/$account{'uid'}");
# samba
&ok_account("displayname", "oliver Mahn");
&ok_account("sambahomepath", "\\\\${server}\\$account{'uid'}");
&ok_account("sambahomedrive", "H:");
&ok_account("sambalogontime", "0");
&ok_account("sambalogofftime", "$win_magic");
&ok_account("sambakickofftime", "$win_magic");
&ok_account("sambapwdcanchange", "0");
&ok_account("sambapwdmustchange", "$win_magic");
&ok_account("sambaacctflags","[U]");
$usid=2*$account{'uidnumber'}+1000;
$gsid=2*$account{'gidnumber'}+1001;
&ok_account("sambasid", "${sid}-${usid}");
&ok_account("sambaprimarygroupsid", "${sid}-${gsid}");



####
####
####  Todo Mahnol should reappear and be merged
####
####



# make the account removeable again


# make user tolerated for a looooong time
&update_user_db_entry($login,"TolerationDate=01.01.1970");

# make account disabled
&run_command("sophomorix-check",$verbose);



# make user deactivated for a looooong time
&update_user_db_entry($login,"DeactivationDate=01.01.1971");

# make account removeable
&run_command("sophomorix-check",$verbose);


#check account again



&run_command("sophomorix-user -K $login",$verbose);
&run_command("sophomorix-check",$verbose);


# todo ?????????ß
&run_command("sophomorix-kill",$verbose);

# todo ??????
#&check_emptyness("sophomorix.kill");


foreach my $login (@logins){
   #&check_account($login,"nonexisting");
}



&log_script_end(@arguments);


###########################################################################
# SUB
###########################################################################

sub ok_account{
    # Hash must be in %account, wich is global in this file
    my ($col, $v) = @_;
    # Make sure that its defined
    if (not defined $account{$col} ){
	$account{$col}="";
    };
    # repace spaces in the sambaaccountflags
    if ($col eq "sambaacctflags"){
       $account{$col}=~s/ //g;
    }
    if ($col eq "creationdate"){
       # use a special regex
       like( $account{$col},qr/^$v.*/, "checking if $v is $col of $account{uid}");
    } else {
       # check for equality
       is( $account{$col},$v, "checking if $v is $col of $account{uid}");
    }
}








