#!/usr/bin/perl -w
# Dieses Script (sophomorix-test) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# Bibliotheken

use strict;
use Getopt::Long;
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
use Sophomorix::SophomorixFiles;
use Sophomorix::SophomorixTest;
use Test::More "no_plan";
Getopt::Long::Configure ("bundling");

# Einlesen der Konfigurationsdatei für Entwickler
#{ package DevelConf ; do "/etc/sophomorix/devel/user/sophomorix-devel.conf"}


system("install -d /root/sophomorix-test");


# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
my $add=0;
my $remove=0;

# Parsen der Optionen
my $testopt=GetOptions(
                "add" => \$add,
    "remove|delete" => \$remove,
          );


# Prüfen, ob Optionen erkannt wurden
&check_options($testopt);


############################################################
# Start
############################################################

# the schueler
my @userlist=(
  "12C;Thurau;Dietrich;12.10.1982;==.*;dietrich thurau;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1982",
  "12C;Altig;Rudi;12.10.1981;==.*;rudi altig;[a-z0-9]{2,};[a-z0-9]{3,};12.10.1981",
  "12C;Bartali;Gino;14.12.1972;==.*;gino bartali;[a-z0-9]{2,};[a-z0-9]{3,};14.12.1972",
  "12C;Coppi;Fausto;12.01.1972;==.*;fausto coppi;[a-z0-9]{2,};[a-z0-9]{3,};12.01.1972",
  "12C;Merckx;Eddy;12.01.1972;==.*;eddy merckx;[a-z0-9]{2,};[a-z0-9]{3,};12.01.1972",
  "12C;Raas;Jan;12.01.1972;==.*;jan raas;[a-z0-9]{2,};[a-z0-9]{3,};12.01.1972",
  "12C;De Vlaminck;Roger;12.01.1972;==.*;roger devlaminck;[a-z0-9]{2,};[a-z0-9]{3,};12.01.1972",
  "12C;Hinault;Bernard;12.01.1972;==.*;bernard hinault;[a-z0-9]{2,};[a-z0-9]{3,};12.01.1972",
  "12C;Kübler;Ferdi;12.01.1972;==.*;ferdi kuebler;[a-z0-9]{2,};[a-z0-9]{3,};12.01.1972",
  "11A;Gillan;Ian;12.01.1972;==.*;ian gillan;[a-z0-9]{2,};[a-z0-9]{3,};12.01.1972",
  "11A;Blackmore;Ritchie;12.01.1978;==.*;ritchie blackmore;[a-z0-9]{2,};[a-z0-9]{3,};12.01.1978",
  "11A;Glover;Roger;14.01.1972;==.*;roger glover;[a-z0-9]{2,};[a-z0-9]{3,};14.01.1972",
  "11A;Lord;Jon;12.02.1972;==.*;jon lord;[a-z0-9]{2,};[a-z0-9]{3,};12.02.1972",
  "11A;Paice;Ian;12.04.1974;==.*;ian paice;[a-z0-9]{2,};[a-z0-9]{3,};12.04.1974",
  "11A;Plant;Robert;12.05.1974;==.*;robert plant;[a-z0-9]{2,};[a-z0-9]{3,};12.05.1974",
  "11A;Page;Jimmy;12.08.1974;==.*;jimmy page;[a-z0-9]{2,};[a-z0-9]{3,};12.08.1974",
  "11A;Jones;John Paul;12.04.1976;==.*;johnpaul jones;[a-z0-9]{2,};[a-z0-9]{3,};12.04.1976",
  "11A;Bonham;John;02.04.1974;==.*;john bonham;[a-z0-9]{2,};[a-z0-9]{3,};02.04.1974",
);

# the lehrer
my @teacherlist=(
  "lehrer;Galilei;Galileo;12.10.1982;galli;==.*;galileo galilei;galli;[a-z0-9]{3,};12.10.1982",
  "lehrer;Bruno;Giordano;12.10.1981;bruno;==.*;giordano bruno;bruno;[a-z0-9]{3,};12.10.1981",
  "lehrer;Kepler;Johannes;12.10.1970;hannes;==.*;johannes kepler;hannes;[a-z0-9]{3,};12.10.1970",
  "lehrer;Kopernikus;Nikolaus;12.10.1976;niko;==.*;nikolaus kopernikus;niko;[a-z0-9]{3,};12.10.1976",
  "lehrer;Brahe;Tycho;12.10.1986;tycho;==.*;tycho brahe;tycho;[a-z0-9]{3,};12.10.1986",
);

# the loginnames of the lehrer
my @loginlist=("tycho", "hannes", "bruno", "galli", "niko" );


my $user="";
my $teacher="";
my $login="";
my $today=`date +%d.%m.%Y`;
print "\nToday is $today";
chomp($today);
my $verbose=0;




###########################################################################
# Do I have to add some users?

if ($add==1 and not -e "/root/sophomorix-test/bunchofusers"){
    print '
###########################################################################
#                                                                         #
#                    ANLEGEN EINIGER SCHÜLER, LEHRER                      #
#                                                                         #
###########################################################################
    ';
    foreach $user (@userlist){
       my ($txt,$proto)=split(/==/, $user);
#       print "TXT       :  $txt \n";
#       print "PROTOKOLL :  $proto \n";
       &append_line("$txt","${DevelConf::users_pfad}/schueler.txt");
    }

    print "Adding students ...\n";
    &run_command("sophomorix-check",$verbose);
    &run_command("sophomorix-add",$verbose);


    foreach $teacher (@teacherlist){
       my ($txt,$proto)=split(/==/, $teacher);
#       print "TXT       :  $txt \n";
#       print "PROTOKOLL :  $proto \n";
       &append_line("$txt","${DevelConf::users_pfad}/lehrer.txt");
    }

    print "Adding teachers ...\n";
    &run_command("sophomorix-check",$verbose);
    &run_command("sophomorix-add",$verbose);


    foreach $user (@userlist){
       my ($txt,$proto)=split(/==/, $user);
#       print "TXT       :  $txt \n";
#       print "PROTOKOLL :  $proto \n";
       my $login=&get_login_name("$proto");
       &check_account($login,"enabled");
    }

    foreach $teacher (@teacherlist){
       my ($txt,$proto)=split(/==/, $teacher);
#       print "TXT       :  $txt \n";
#       print "PROTOKOLL :  $proto \n";
       my $login=&get_login_name("$proto");
       &check_account($login,"enabled");
    }

    # Marking the added users
    system("touch /root/sophomorix-test/bunchofusers");
} elsif ($add==1 and -e "/root/sophomorix-test/bunchofusers"){
    print "The users are added already!\n";
} else {
    print "Not adding users!\n";
}


###########################################################################
# Do I have to remove some users?


if ($remove==1 and -e "/root/sophomorix-test/bunchofusers"){
    print '
###########################################################################
#                                                                         #
#                ENTFERNEN ANGELEGTER SCHÜLER, LEHRER                     #
#                                                                         #
###########################################################################
    ';

    foreach $user (@userlist){
        my ($txt,$proto)=split(/==/, $user);
        &remove_line(
                "$txt",
                "${DevelConf::users_pfad}/schueler.txt");
    }




    foreach $login (@loginlist){
        #my ($txt,$proto)=split(/==/, $teacher);
        &remove_line(
                ";$login",
                "${DevelConf::users_pfad}/lehrer.txt");
    }

    &run_command("sophomorix-check",$verbose);

    foreach $user (@userlist){
        my ($txt,$proto)=split(/==/, $user);
        my $login=&get_login_name("$proto");
        &update_user_db_entry($login,"TolerationDate=01.01.1970");
    }

    foreach $teacher (@teacherlist){
        my ($txt,$proto)=split(/==/, $teacher);
        my $login=&get_login_name("$proto");
        &update_user_db_entry($login,"TolerationDate=01.01.1970");
    }

    &run_command("sophomorix-check",$verbose);
    &run_command("sophomorix-move",$verbose);


    foreach $user (@userlist){
        my ($txt,$proto)=split(/==/, $user);
        my $login=&get_login_name("$proto");
        &update_user_db_entry($login,"DeactivationDate=01.01.1971");
    }

    foreach $teacher (@teacherlist){
        my ($txt,$proto)=split(/==/, $teacher);
        my $login=&get_login_name("$proto");
        &update_user_db_entry($login,"DeactivationDate=01.01.1971");
    }

    &run_command("sophomorix-check",$verbose);
    &run_command("sophomorix-kill",$verbose);

    system("rm /root/sophomorix-test/bunchofusers");
} elsif($remove==1 and not -e "/root/sophomorix-test/bunchofusers") {
    print "The users are removed already!\n";

} else {
    print "Not removing users!\n";
}
