#!/usr/bin/perl -w
# Dieses Script (sophomorix-test) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# Bibliotheken

use strict;
use Getopt::Long;
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
use Sophomorix::SophomorixPgLdap;
use Sophomorix::SophomorixTest;
use Test::More "no_plan";
Getopt::Long::Configure ("bundling");

use DBI;

# Einlesen der Konfigurationsdatei für Entwickler
#{ package DevelConf ; do "/etc/sophomorix/devel/user/sophomorix-devel.conf"}


system("install -d /root/sophomorix-test");

my $dirname="";
my $linkname="";
my $mothergroup="";

my $file="";
my @teacher_files=();
my @userlist_to_check=();

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
my $add=0;
my $wsadd=0;
my $remove=0;
my $wsremove=0;
my $work=0;

# Parsen der Optionen
my $testopt=GetOptions(
                "add" => \$add,
                "wsadd" => \$wsadd,
                "work" => \$work,
                "remove|delete" => \$remove,
                "wsremove|wsdelete" => \$wsremove,
          );


# Prüfen, ob Optionen erkannt wurden
&check_options($testopt);


############################################################
# Start
############################################################

# ACHTUNG:
#  -  Keine Sonderzeichen
#  -  Korrektes Datumsformat

# the schueler
my @userlist=(
  "12C;Thurau;Dietrich;12.10.1982;",
  "12C;Altig;Rudi;12.10.1981;",
  "12C;Bartali;Gino;14.12.1972;",
  "12C;Coppi;Fausto;12.01.1972;",
  "12C;Merckx;Eddy;12.01.1972;",
  "12C;Raas;Jan;12.01.1972;",
  "12C;DeVlaminck;Roger;12.01.1972;",
  "12C;Hinault;Bernard;12.01.1972;",
  "12C;Kuebler;Ferdi;12.01.1972;",
  "11A;Gillan;Ian;12.01.1972;",
  "11A;Blackmore;Ritchie;12.01.1978;",
  "11A;Glover;Roger;14.01.1972;",
  "11A;Lord;Jon;12.02.1972;",
  "11A;Paice;Ian;12.04.1974;",
  "11A;Plant;Robert;12.05.1974;",
  "11A;Page;Jimmy;12.08.1974;",
  "11A;Jones;JohnPaul;12.04.1976;",
  "11A;Bonham;John;02.04.1974;",
);

# the lehrer
my @teacherlist=(
  "lehrer;Galilei;Galileo;12.10.1982;galli;",
  "lehrer;Bruno;Giordano;12.10.1981;bruno;",
  "lehrer;Kepler;Johannes;12.10.1970;hannes;",
  "lehrer;Kopernikus;Nikolaus;12.10.1976;niko;",
  "lehrer;Brahe;Tycho;12.10.1986;tycho;",
);

# the loginnames of the lehrer
my @loginlist=("tycho", "hannes", "bruno", "galli", "niko" );


#my $user="";
my $teacher="";
my $login="";
my $today=`date +%d.%m.%Y`;
print "\nToday is $today";
chomp($today);
my $verbose=0;




###########################################################################
# Do I have to add some users?

if ($add==1 and not -e "/root/sophomorix-test/bunchofusers"){
    print '
###########################################################################
#                                                                         #
#                    ANLEGEN EINIGER SCHÜLER, LEHRER                      #
#                                                                         #
###########################################################################
    ';
    foreach my $user (@userlist){
       #my ($txt,$proto)=split(/==/, $user);
       &append_line("$user","${DevelConf::users_pfad}/schueler.txt");
    }

    print "Adding students ...\n";
    &run_command("sophomorix-check",$verbose);
    &run_command("sophomorix-add",$verbose);
    # 2x add bug in db ????????
    &run_command("sophomorix-add",$verbose);


    foreach my $teacher (@teacherlist){
       #my ($txt,$proto)=split(/==/, $teacher);
       &append_line("$teacher","${DevelConf::users_pfad}/lehrer.txt");
    }

    print "Adding teachers ...\n";
    &run_command("sophomorix-check",$verbose);
    &run_command("sophomorix-add",$verbose);


    foreach my $user (@userlist){
       my $login=&get_login_from_user($user);    
       # todo ??????
       #&check_account($login,"enabled");
    }


    foreach my $teacher (@teacherlist){
       my $login=&get_login_from_user($teacher);    
       # todo ??????
       #&check_account($login,"enabled");
    }


    # creating some projects
    system("sophomorix-project --create -p astro --Longname Astronomie --Admins tycho,niko --Members altigru,thuraudi,blackmri,pageji");
    system("sophomorix-project --create -p chemie --Longname Chemie-AG --Admins bruno,tycho --Members altigru,thuraudi,hannes,lordjo,gillania");
    system("sophomorix-project --create -p micro --Longname Mikroskopie --Admins hannes --Members altigru,thuraudi,hinaulbe,raasja");

    # teacher tycho and bruno join a class 
    system("sophomorix-teacher --teacher bruno --add 11a");
    system("sophomorix-teacher --teacher tycho --add 11a");

    # creating 2 subclasses  in class 11a 
    system("sophomorix-subclass --split --noninteractive --class 11a  --AMembers gillania,blackmri,gloverro,paiceia,lordjo --BMembers plantro,pageji,jonesjo,bonhamjo");


    # Marking the added users
    system("touch /root/sophomorix-test/bunchofusers");
} elsif ($add==1 and -e "/root/sophomorix-test/bunchofusers"){
    print "The users are added already!\n";
} else {
    print "INFO: Not adding users!\n";
}




my $workstationhome="/home/workstations";
my $room1="134a";
my $room2="717b";

my @hostnames1=("pc0001","pc0002","pc0003","pc0004");
my @hostnames2=("Rechner1","Rechner2","Rechner3","Rechner4",
                "Rechner5","Rechner6","Rechner7","Rechner8");


if ($wsadd==1){
    print '
###########################################################################
#                                                                         #
#                    ANLEGEN EINIGER WORKSTATION-ACCOUNTS                 #
#                                                                         #
###########################################################################
';
   system("smbldap-groupadd -a $room1");
   system("smbldap-groupadd -a $room2");
   system("mkdir -p $workstationhome/$room1");
   system("mkdir -p $workstationhome/$room2");
   foreach my $hostname (@hostnames1){
      print "Adding $hostname to $room1\n";
      my $command=
         "smbldap-useradd -a -d $workstationhome/$room1/$hostname".
         " -c 'workstation account' -g $room1 -m -s /bin/false $hostname";
      #print "$command\n";
      system("$command");
      $command=
         "smbldap-useradd -w -g 515 -c 'domain machine account'".
         " -d /dev/null -s /bin/false $hostname\$";
      #print "$command\n";
      system("$command");
   }
   foreach my $hostname (@hostnames2){
      print "Adding $hostname to $room2\n";
      my $command=
         "smbldap-useradd -a -d $workstationhome/$room2/$hostname".
         " -c 'workstation account' -g $room2 -m -s /bin/false $hostname";
      #print "$command\n";
      system("$command");
      $command=
         "smbldap-useradd -w -g 515 -c 'domain machine account'".
         " -d /dev/null -s /bin/false $hostname\$";
      #print "$command\n";
      system("$command");
   }
} else {
    print "INFO: Not adding workstation users!\n";
}





if ($wsremove==1){
    print '
###########################################################################
#                                                                         #
#                    LÖSCHEN EINIGER WORKSTATION-ACCOUNTS                 #
#                                                                         #
###########################################################################
';
   foreach my $hostname (@hostnames1){
      print "Deleting $hostname\n";
      my $command=
         "smbldap-userdel -r $hostname";
      #print "$command\n";
      system("$command");
      $command=
         "smbldap-userdel $hostname\$";
      #print "$command\n";
      system("$command");
   }
   foreach my $hostname (@hostnames2){
      print "Deleting $hostname\n";
      my $command=
         "smbldap-userdel -r $hostname";
      #print "$command\n";
      system("$command");
      $command=
         "smbldap-userdel $hostname\$";
      #print "$command\n";
      system("$command");


   }
   system("smbldap-groupdel $room1");
   system("smbldap-groupdel $room2");
   system("rmdir $workstationhome/$room1");
   system("rmdir $workstationhome/$room2");
} else {
    print "INFO: Not removing workstation users!\n";
}





if ($work==1 and -e "/root/sophomorix-test/bunchofusers"){
    print '
###########################################################################
#                                                                         #
#             DO SOME WORK (Vorlagen bereitstellen: class)                #
#                                                                         #
###########################################################################
    ';

   # DISTRIBUTE (Vorlagen)
   my $vorlagen_teacher="galli";
   my $vorlagen_gruppe="11a";
   my $type="adminclass";

   # Working with these files
   @teacher_files=("testfile_1.txt","testfile_2.txt");
   @userlist_to_check=("blackmri",
                       "bonhamjo",
                       "gillania",
                       "gloverro",
                       "jonesjo",
                       "lordjo",
                       "pageji",
                       "paiceia",
                       "plantro");

   &vorlagen_bereitstellen($vorlagen_teacher,
                           $vorlagen_gruppe,
                           $type);

    print '
###########################################################################
#                                                                         #
#             DO SOME WORK (Vorlagen bereitstellen: project)              #
#                                                                         #
###########################################################################
    ';

   # DISTRIBUTE (Vorlagen)
   $vorlagen_teacher="niko";
   $vorlagen_gruppe="astro";
   $type="project";

   # Working with these files
   @teacher_files=("testfile_3.txt","testfile_4.txt");
   @userlist_to_check=("tycho",
                       "niko",
                       "altigru",
                       "thuraudi",
                       "blackmri",
                       "pageji");

   $dirname="Astronomie";
   $linkname="Astronomie";

   &vorlagen_bereitstellen($vorlagen_teacher,
                           $vorlagen_gruppe,
                           $type);
    exit;
    print '
###########################################################################
#                                                                         #
#             DO SOME WORK (Vorlagen bereitstellen: subclass)             #
#                                                                         #
###########################################################################
    ';

   # DISTRIBUTE (Vorlagen)
   $vorlagen_teacher="bruno";
   $vorlagen_gruppe="11a-A";
   $type="subclass";

   # Working with these files
   @teacher_files=("testfile_3.txt","testfile_4.txt");
   @userlist_to_check=("bruno",
                       "tycho",
                       "gillania",
                       "blackmri",
                       "gloverro",
                       "paiceia",
                       "lordjo");

   $dirname="11a-A";
   $linkname="11a-A";
   $mothergroup="11a";

   &vorlagen_bereitstellen($vorlagen_teacher,
                           $vorlagen_gruppe,
                           $type);




    print '
###########################################################################
#                                                                         #
#       DO SOME WORK (Dateien einsammeln: niko von 12c, moven)            #
#                                                                         #
###########################################################################
';

   # COLLECT move (Vorlagen)
   my $einsammeln_teacher="niko";
   my $einsammeln_gruppe="12c";
   my $einsammeln_type="adminclass";
   my $einsammeln_option="collect";

   # Working with these files
   @teacher_files=("testfile_1.txt","testfile_2.txt");
   @userlist_to_check=("altigru",
                       "bartalgi",
                       "coppifa",
                       "devlamro",
                       "hinaulbe",
                       "kueblefe",
                       "merckxed",
                       "raasja",
                       "thuraudi");

   &dateien_einsammeln($einsammeln_teacher,
                       $einsammeln_gruppe,
                       $einsammeln_type,
                       $einsammeln_option);



    print '
###########################################################################
#                                                                         #
#    DO SOME WORK (Dateien einsammeln: galli von 11a, collectcopy)        #
#                                                                         #
###########################################################################
';

   # COLLECT copy (Vorlagen)
   $einsammeln_teacher="galli";
   $einsammeln_gruppe="11a";
   $einsammeln_type="adminclass";
   $einsammeln_option="collectcopy";

   # Working with these files
   @teacher_files=("testfile_1.txt","testfile_2.txt");
   @userlist_to_check=("blackmri",
                       "bonhamjo",
                       "gillania",
                       "gloverro",
                       "jonesjo",
                       "lordjo",
                       "pageji",
                       "paiceia",
                       "plantro");


   &dateien_einsammeln($einsammeln_teacher,
                       $einsammeln_gruppe,
                       $einsammeln_type,
                       $einsammeln_option);




    print '
###########################################################################
#                                                                         #
# DO SOME WORK (Dateien einsammeln: galli von project astro, collectcopy) #
#                                                                         #
###########################################################################
';


   # COLLECT copy (Vorlagen) from project
   $einsammeln_teacher="niko";
   $einsammeln_gruppe="astro";
   $einsammeln_type="project";
   $einsammeln_option="collectcopy";

   # Working with these files
   @teacher_files=("testfile_1.txt","testfile_2.txt");
   @userlist_to_check=("altigru",
                       "blackmri",
                       "pageji",
                       "thuraudi");

   &dateien_einsammeln($einsammeln_teacher,
                       $einsammeln_gruppe,
                       $einsammeln_type,
                       $einsammeln_option);

    print '
###########################################################################
#                                                                         #
#            DO SOME WORK (Dateien austeilen an userliste)                #
#                                                                         #
###########################################################################
';

   # COLLECT copy (Vorlagen) from project
   my $handout_teacher="niko";

   # Working with these files
   @teacher_files=("testfile_2.txt","testfile_3.txt");
   @userlist_to_check=("altigru",
                       "blackmri",
                       "pageji",
                       "thuraudi");
   my $userliste="altigru,blackmri,pageji,thuraudi";


   &handout_files_room($handout_teacher,$userliste);   



   exit;



   # Distribute copy to userlist
   $einsammeln_teacher="niko";




} elsif ($work==1 and not -e "/root/sophomorix-test/bunchofusers"){
    print "The users must be added bofore doing some work!\n";
} else {
    print "INFO: Not doing any work the users!\n";
}







###########################################################################
# Do I have to remove some users?


if ($remove==1 and -e "/root/sophomorix-test/bunchofusers"){
    print '
###########################################################################
#                                                                         #
#                ENTFERNEN ANGELEGTER SCHÜLER, LEHRER                     #
#                                                                         #
###########################################################################
';
    # removing projects
    system("sophomorix-project --kill -p astro");
    system("sophomorix-project --kill -p chemie");
    system("sophomorix-project --kill -p micro");



    # removing users
    foreach my $user (@userlist){
        &remove_line(
                "$user",
                "${DevelConf::users_pfad}/schueler.txt");
    }


    foreach my $teacher (@loginlist){
        &remove_line(
                ";$teacher",
                "${DevelConf::users_pfad}/lehrer.txt");
    }


    &run_command("sophomorix-check",$verbose);

    foreach my $user (@userlist){
        my $login=&get_login_from_user($user);    
        &update_user_db_entry($login,"TolerationDate=01.01.1970");
    }

    foreach my $teacher (@teacherlist){
        my $login=&get_login_from_user($teacher);    
        &update_user_db_entry($login,"TolerationDate=01.01.1970");
    }

    &run_command("sophomorix-check",$verbose);
    &run_command("sophomorix-move",$verbose);


    foreach my $user (@userlist){
        my $login=&get_login_from_user($user);    
        &update_user_db_entry($login,"DeactivationDate=01.01.1971");
    }

    foreach my $teacher (@teacherlist){
        my $login=&get_login_from_user($teacher);    
        &update_user_db_entry($login,"DeactivationDate=01.01.1971");
    }

    &run_command("sophomorix-check",$verbose);
# todo ?????
    &run_command("sophomorix-kill",$verbose);

    system("rm /root/sophomorix-test/bunchofusers");
} elsif($remove==1 and not -e "/root/sophomorix-test/bunchofusers") {
    print "The users are removed already!\n";

} else {
    print "INFO: Not removing users!\n";
}






############################################################
# SUB
############################################################
sub dateien_einsammeln{
    my ($teacher,$group,$type,$option) = @_;
    my $command="";
    print "Cleaning up $teacher \n";
#    $command="rm -rf /home/teachers/${teacher}/${Language::collect_dir}/${group}/*"; 
    $command="sophomorix-user --reset-user $teacher";
    print "$command \n";
    system($command);




    foreach my $user (@userlist_to_check){
       print "Cleaning up $user \n";
       my @entry = getpwnam($user);
       my $homedir = "$entry[7]";

#       $command="rm -rf /home/students/${dirname}/${user}/${Language::collect_dir}/*"; 
#       $command="rm -rf $homedir/${Language::collect_dir}/*"; 
       $command="sophomorix-user --reset-user $user";
       print "$command \n";
       system($command);
    }

    foreach my $testfile (@teacher_files){
       foreach my $user (@userlist_to_check){
       my @entry = getpwnam($user);
       my $homedir = "$entry[7]";

          $command="su --command='cp /usr/share/sophomorix-developer/testfiles/${testfile} /home/students/${dirname}/${user}/${Language::collect_dir}'";
          $command="su --command='cp /usr/share/sophomorix-developer/testfiles/${testfile} ${homedir}/${Language::collect_dir}'";
          print "$command \n";
          system($command);
       }
    }

    # collect files(?????? later do this as galli)
    $command="sophomorix-teacher --teacher $teacher --collect --${type} $group";

    print "$command \n";
    system($command);

    my $collect_dir="";
    my $collect_parent_dir=
        "/home/teachers/${teacher}/${Language::collect_dir}/${group}";
    print "$collect_parent_dir \n";
    opendir(COLL, $collect_parent_dir) 
         || die "can't opendir ",
                "$/home/teachers/${teacher}/${Language::collect_dir}/${group} $!";
    while (defined(my $filename = readdir(COLL))) {
        #print "Directory $filename found\n";
        if ($filename=~m/^${group}.*$/){
          $collect_dir=$filename
	  }
    }
    closedir(COLL);
    
    print "Looking for collected data in $collect_dir \n";

    foreach my $user (@userlist_to_check){
        foreach my $testfile (@teacher_files){
           $file="/home/teachers/${teacher}/${Language::collect_dir}/${group}/${collect_dir}/${user}/${testfile}"; 
           &check_existence($file);
           $file="/home/students/${group}/${user}/${Language::collect_dir}/${testfile}"; 

           if ($option eq "collect"){
               # data must be moved away
               &check_nonexistence($file);
           } elsif ($option eq "collectcopy"){
               # data must be there
               &check_nonexistence($file);
           } else {
	       print "Bad option $option";
               exit;
           }
	}
    }
}


sub vorlagen_bereitstellen{
    # howto:
    # class:   $linkname is $group
    #          $dirname is $group       
    # project: $linkname    # must be given before calling
    #          $dirname     # vorlagen_bereitstellen
    # subclass:$linkname    # must be given before calling
    #          $dirname     # vorlagen_bereitstellen
    my ($teacher,$group,$type) = @_;
    print "Cleaning up $teacher \n";
    my $command="";
    my $file="";

    if ($type eq "project"){
       # $linkname (global should be given before calling this function) 
       # $dirname  (global should be given before calling this function) 
       # $mothergroup (global should be given before calling this function) 
    } elsif ($type eq "subclass"){
       # $linkname (global should be given before calling this function) 
       # $dirname  (global should be given before calling this function) 
       # $mothergroup (global should be given before calling this function) 
    } else {
       $linkname=$group;  
       $dirname=$group;  
       $mothergroup=$group;
    }

    # romove the teacher from this class
    if ($type eq "adminclass" or $type eq "subclass"){
        $command="sophomorix-teacher --teacher $teacher --remove $mothergroup";
        print "$command \n";
        system($command);
    }

    #$command="rm -rf /home/teachers/${teacher}/${Language::handout_dir}/${group}"; 

    $command="sophomorix-user --reset-user $teacher";
    print "$command \n";
    system($command);


    # do this with add already
    # join the class 11a (?????? later do this as galli)
    if ($type eq "adminclass"){
       $command="sophomorix-teacher --teacher $teacher --add $group";
       print "$command \n";
       system($command);
    } elsif ($type eq "subclass"){
       $command="sophomorix-teacher --teacher $teacher --add $mothergroup";
       print "$command \n";
       system($command);
    }

    # was directory created ?
    $file="/home/teachers/${teacher}/${Language::handout_dir}/${dirname}"; 
    ok(-e $file, "$file existiert");

    foreach my $testfile (@teacher_files){
        $command="su --command='cp /usr/share/sophomorix-developer/testfiles/${testfile} /home/teachers/${teacher}/${Language::handout_dir}/${dirname}'/";
        print "$command \n";
        system($command);
    }

    # distribute files(?????? later do this as galli)
    $command="sophomorix-teacher --teacher $teacher --handout --${type} $group";
    print "$command \n";
    system($command);

    # was file handed out ?
    foreach my $testfile (@teacher_files){
       foreach my $user (@userlist_to_check){
          # home ermitteln
          my @entry = getpwnam($user);
          my $homedir = "$entry[7]";


          $file="${homedir}/${Language::task_dir}/${Language::task_string}".
                "${linkname}/${teacher}/${testfile}"; 
          ok(-e $file, "$file existiert");
       }
    }


}





sub handout_files_room {
    my ($teacher,$users) = @_;
    my @users = split(/,/,$users);
    my $command="";

    # clean up
    $command="rm -rf /home/teachers/${teacher}/${Language::handoutcopy_dir}/aktueller_raum/*"; 
    print "$command \n";
    system($command);
 
    foreach my $user (@users){
       print "$user","\n";
       my @entry = getpwnam($user);
       my $homedir = "$entry[7]";
       $command="rm -rf ${homedir}/${Language::handoutcopy_dir}/aktueller_raum/*"; 
       print "$command \n";
       system($command);
    } 

    foreach my $testfile (@teacher_files){
       $command="su --command='cp /usr/share/sophomorix-developer/testfiles/${testfile} /home/teachers/${teacher}/${Language::handoutcopy_dir}/aktueller_raum'";
       print "$command \n";
       system($command);
    }

    $command="sophomorix-teacher --teacher $teacher --user $users --fromroom --handoutcopy";
    print "$command \n";
    system($command);
    foreach my $user (@userlist_to_check){
       foreach my $testfile (@teacher_files){
         my @entry = getpwnam($user);
         my $homedir = "$entry[7]";
         my $file="$homedir/${Language::handoutcopy_dir}/aktueller_raum/$testfile";
         &check_existence($file);
       }
    }
}





sub get_login_from_user {
    my ($user) = @_;
    my $login="";
    my ($class,$last,$first,$birth)=split(/;/,$user);
    $class=~tr/A-Z/a-z/; # in Kleinbuchstaben umwandeln
    if ($class eq "lehrer"){
        $class="teachers",
    }
    $last=~tr/A-Z/a-z/; # in Kleinbuchstaben umwandeln
    $first=~tr/A-Z/a-z/; # in Kleinbuchstaben umwandeln

    $birth=&date_perl2pg($birth);

    # Fetch login of user
    $login = &fetch_login("surname='$last' 
                          AND firstname='$first'
                          AND birthday='$birth'",
                         );
    return $login;
}
