#!/usr/bin/perl -w
# Dieses Script (sophomorix-minitest) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# Dieses Script ist NICHT im Paket sophomorix-developer enthalten



# Bibliotheken
use strict;
use Getopt::Long;
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
use Sophomorix::SophomorixAPI;
#use Sophomorix::SophomorixFiles;
use Sophomorix::SophomorixPgLdap;
use Sophomorix::SophomorixTest;
use Test::More "no_plan";
Getopt::Long::Configure ("bundling");

use DBI;
use Crypt::SmbHash;
use Net::LDAP;
#use DebAux::Debconf;
use IMAP::Admin;

my $cyruspass="NMnDwk1U";
my $cyrususer="cyrus";

my $user="ohenryhigg";


my $imap=&imap_connect("localhost",$cyrususer,$cyruspass);


# fetch list of mailboxes
&imap_show_mailbox_info($imap);

&imap_kill_mailbox($imap,"ohenryhigg");

exit;

# create mailbox
&imap_create_mailbox($imap,$user);


# setting quota
my @mailquota=&imap_fetch_mailquota($imap,$user);
&imap_set_mailquota($imap,$user,"30");
@mailquota=&imap_fetch_mailquota($imap,$user);




&imap_disconnect($imap);

############################################################
# sub
############################################################
