#!/usr/bin/perl -w
# Dieses Script (sophomorix-minitest) wurde von Rüdiger Beck erstellt
# Es ist freie Software
# Bei Fehlern wenden Sie sich bitte an mich.
# jeffbeck@web.de  oder  jeffbeck@gmx.de

# Dieses Script ist NICHT im Paket sophomorix-developer enthalten



# Bibliotheken
use strict;
use Getopt::Long;
use Sophomorix::SophomorixConfig;
use Sophomorix::SophomorixBase;
use Sophomorix::SophomorixAPI;
#use Sophomorix::SophomorixFiles;
use Sophomorix::SophomorixPgLdap;
use Sophomorix::SophomorixTest;
use Test::More "no_plan";
Getopt::Long::Configure ("bundling");

use DBI;
use Crypt::SmbHash;
use Net::LDAP;
#use DebAux::Debconf;
use IMAP::Admin;



#&chmod_chown_dir_smb("/root/find","0701","0005","devlamro","12a");

#&fetch_smb_conf();

#my ($path,$dir_perm,$file_perm,$owner,$gowner)=&show_smb_conf_umask("cdrom");


#print " Path:  $path\n";
#print " dirs:  $dir_perm\n";
#print " files: $file_perm\n";
#print " owner: $owner\n";
#print " gowner: $gowner\n";


#&chmod_chown_dir("/root/find",$dir_perm,$file_perm,$owner,$gowner);

#my ($dir,$file) = &permissions_from_umask();

#print "Dir $dir     File $file \n";

#my ($home,$type)=&Sophomorix::SophomorixPgLdap::fetchdata_from_account("nikoob");

#print "$home   $type  \n";


#&update_user_db_entry("shoemaca","Uid=schumacher");

#&lehrer_ordnen("gilli","galli");

&cyrus_connect;

exit;

my $old_ho="\\\\server\\merckxed";

print "${old_ho}\n";


my $old="merckxed";
my $new="edmrxle";

#$old_ho=~s/\\${old}$/\\\\${new}/;
#$old_ho=~s/^\\\\/\\\\\\\\/;



print "${old_ho}\n";


############################################################
# sub
############################################################
