.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOPHOMORIX-TEST-BUNCHOFUSERS 8 "November 29, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sophomorix-test-bunchofusers \- Anlegen und entfernen von Beispiel-Klassen
und -Lehrer
.SH SYNOPSIS
.B sophomorix-test-bunchofusers
.br
.SH DESCRIPTION
.B sophomorix-test-bunchofusers
.RI [ options ] 
.br
sophomorix-test-bunchofusers legt zwei Klassen und 4 Lehrer an.
.br
Es wird kurz getestet, ob dies erfolgreich war.
.br
Am Ende können diese User wieder entfernt werden, wenn an ihnen keine
Änderungen vorgenommen wurden.
.br
Ansonsten müssen sie manuell entfernt werden:
.br
   1. Entfernen aus schueler.txt und lehrer.txt
.br
   2. sophomorix-user -K loginname
.br
   3. sophomorix-check
.br
   4. sophomorix-kill
.br
Dieser Test ist nicht geeignet um auf einem produktiven Server
ausgeführt zu werden.
.br
Er dient lediglich dazu zum herumspielen und für Eigentests schnell
einen Haufen User zu erzeugen.
.SH OPTIONS
.B sophomorix-bunchofusers
benützt die GNU command line syntax, mit langen Optionen, die mit zwei
Bindestrichen (`-') beginnen:
.TP
.B --add
Legt die beiden Klassen und Lehrer an
.TP
.B --remove, --delete
Entfernt die beiden Klassen und Lehrer wieder, falls keine
Namensänderungen getestet wurden.
.TP

.PP
.TP
.SH SEE ALSO
.BR sophomorix (8),
.BR sophomorix-teach-in (8),
.BR sophomorix-add (8),
.BR sophomorix-move (8),
.BR sophomorix-kill (8),
.BR sophomorix-print (8),
.BR sophomorix-user (8),
.BR sophomorix-split (8),
.BR sophomorix-project (8),
.SH AUTHOR
This manual page was written by <jeffbeck@web.de>.
