.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ITALCROOMS.CONF 5 "January 17, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
/etc/sophomorix/italc/italcrooms.conf \- Konfigurationsdatei für sophomorix-workstation --italcdir did
.br
.SH DESCRIPTION
Diese Datei beschreibt die Syntax der Datei italcrooms.conf, in der festgelegt wird, in welchen Räumen welche Linux clients italc in welcher Weise (master, slave) benutzen können.

.PP
.SH FELDER

Die folgenden Felder bilden eine Zeile, die durch Strichpunkte getrennt sind:
.TP
.B Feld 1: Raumname
Der Raumname muss genauso lauten, wie in der Workstationsdatei angeben.
.TP
.B Feld 2: Raumname italc
Raumname des Raums von Feld 1, wie er in italc angezeigt werden soll.
.TP
.B Feld 3: Lehrererechner
Rechnernamen des Raumes von Feld 1, die via italc auf die anderen Rechner des gleichen Raumes zugreifen können (Italc Master). Der Rechnername muss so lauten, wie in der Workstationsdatei angeben
.br 
Durch Komma separiert können mehrere Rechhernamen angegeben werden.
.TP
.B Feld 4: Invisible Hosts
Rechner des Raumes von Feld 1, die in italc unsichtbar sein sollen.
.TP

.SH AUTHOR
Written by <jeffbeck@web.de>.
