.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SCHUELER.TXT 5 "April 25, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
/etc/sophomorix/user/schueler.txt \- Konfigurationsdatei für die
Schüleraccounts bei linuxmuster.net
.br
.SH DESCRIPTION
Um den Sollzustand einfacher User vorzugeben werden diese in der Datei
schueler.txt konfiguriert.

Leerzeichen in Namen und Klasse werden entfernt.

Klassenbezeichnung wird in Kleinbuchstaben umgewandelt


.PP
.SH FELDER

Die folgenden Felder bilden eine Zeile, die durch Strichpunkte
getrennt abgeschlosse werden:
.TP
.B Feld 1: Klasse des Users.
.TP
.B Feld 2: Nachname des Users
.TP
.B Feld 3: Vorname des Users
.TP
.B Feld 4: Geburtsdatum des user im Format dd.mm.yyyy
.TP
.B Feld 5: Eindeutiger Identifikationsstring des users der sich nicht ändert (Optional)
.br 
Zum Beispiel die Datenbank ID des Schulverwaltungsprogramms.
.TP
.B Feld 6: Abteilung (Optional, bisher nicht genutzt)
.TP
.SH SEE ALSO
.BR sophomorix-check (8)
.
.SH AUTHOR
Written by <jeffbeck@web.de>.
