.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOPHOMORIX-JANITOR 8 "October 09, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sophomorix-janitor \- Hausmeister von sophomorix
.SH SYNOPSIS
.B sophomorix-janitor
.RI [ options ]
.br
.SH DESCRIPTION
.B sophomorix-janitor  
bereinigt sophomorix von ungenutzen Daten, z.B. am Schuljahresende
.br
WARNUNG:Im Moment ist sophomorix-janitor noch experimentell. Es wird
empfohlen, dass man Daten erst entfernt nachdem man sich überzeugt
hat, dass sie nicht mehr benötigt werden.
.PP
.SH ALLGEMEINE OPTIONEN
.B sophomorix-janitor
benützt die GNU command line syntax, mit langen Optionen, die mit zwei
Bindestrichen (`-') beginnen:
.TP
.B \-h, \-\-help
Kurzübersicht über Optionen, sowie eine Liste der eingelesenen Dateien.
.TP
.B \-v, \-\-verbose
Sagt, was das Programm gerade macht (verbose)
.TP
.B \-vv, \-\-verbose \-\-verbose
Sagt ungeheuer genau, was das Programm gerade macht (very verbose)
.SH DATEIEN ZUM BEGUTACHTEN KOPIEREN/VERSCHIEBEN 
Beim Begutachten wird mit den Daten EINES Users folgendes gemacht:
. IP \(em 3
Die Daten werden beim kopieren/verschieben dem User root
überantwortet. Damit wird das Festplatten-Quota es Users entlastet.
. IP \(em
Beim Verschieben werden die Daten exakt gleich wie beim Kopieren
zuerst ans Ziel kopiert. Danach werden allerdings die Quelldaten
gelöscht.
. IP \(em
Im Zielverzeichnis gibt es das
Log-Verzeichnis .sophomorix-janitor. Dort finden sich die
Informationen, die beim verschieben verloren gehen würden (owner,
groupowner, atime, mtime, ctime der Quelledaten).
. IP \(em
In Zukunft wird es ein cronjob geben, der nach der abgelaufenen Zeit
die zu begutachtenden Daten löscht.
.TP
Zeitlicher Ablauf:
.TP
. IP \(em 
Schritt 1: Dateien werden mit demselben relativen Pfad
kopiert/verschoben. Dazu benötigte übergeordnete Verzeichnisse werden
angelegt.
. IP \(em
Schritt 2: Verzeichnisse brauchen wegen Schritt 1 nicht mehr kopiert
zu werden. Beim Verschieben werden leere Verzeichnisse der Quelle
entfernt. Nichtleere Verzeichnisse der Quelle werden dem user
überantwortet, der in der obersten Verzeichnisebene dieses
Verzeichnises die meisten Daten besitzt.
. IP \(em
Schritt 3: Links werden nicht kopiert/verschoben.
. IP \(em
Schritt 4: Alle restlichen Daten werden nicht kopiert/verschoben.
.br 
.SH GRUNDLEGENDE OPTIONEN ZUM BEGUTACHTEN:
Optionen mit Angabe des Zielverzeichnisses: 
.TP
.in 3
.B --find-files /quelle --owner uid
Auflisten der Daten eines Users im Verzeichnis /quelle
.TP 
.in 3 
.B --find-files /quelle --owner uid --copy-to /ziel
Kopieren der Daten eines Users vom Verzeichnis /quelle nach /ziel
.TP 
.in 3
.B --find-files /quelle --owner uid --move-to /ziel
Verschieben der Daten eines Users vom Verzeichnis /quelle nach /ziel
.TP 
Mit Zielverzeichnis /quelle/login_bleibt_erhalten_bis_DATUM:
.TP 
.in 3
.B --copy-to-review /quelle --owner uid --review-days num
Kopieren der Daten eines Users im Verzeichnis /quelle
.TP 
.in 2
.B --move-to-review /quelle --owner uid --review-days num
Verschieben der Daten eines Users im Verzeichnis /quelle
.TP
Die Option --review-days ist optional. Standardwert: 366 Tage.
.TP
Die Option --uid kann sowohl uid-Name als auch uid-Number enthalten. 
.br
.SH SHORTCUT-OPTIONEN ZUM BEGUTACHTEN
.TP
Begutachten der Dateien in $HOME eines Users:
.TP 
.in 3
.B --move-to-review-home login --review-days num
.TP
.in 3
.B --copy-to-review-home login --review-days num
.TP
Begutachten der Dateien im Tauschverzeichnis der Lehrer:
.TP 
.in 3
.B --move-to-review-teacher login --review-days num
.TP
.in 3
.B --copy-to-review-teacher login --review-days num
.TP
Die Option --review-days ist optional. Standardwert: 366 Tage.
.TP
Begutachten der Dateien in allen Projekt-Tausch-Verzeichnissen:
.TP 
.in 3
.B --move-to-review-share-project login --review-days num
.TP
.in 3
.B --copy-to-review-share-project login --review-days num
.TP
Begutachten der Dateien in allen Klassen-Tausch-Verzeichnissen:
.TP 
.in 3
.B --move-to-review-share-class login --review-days num
.TP
.in 3
.B --copy-to-review-share-class login --review-days num
.br
.SH OPTIONEN FÜR DATENBANK TOOLS:
.TP 
.B --check-horde
Sucht in der Horde3-Datenbank in der Tabelle horde_prefs nach
Einträgen von usern, die im System nicht mehr existieren.
.TP
.B --dump-pg-ldap
Dumpt die pstgresql Datenbank ldap der Benutzerverwaltung mit
Datumsstempel ins übliche Verzeichnis.
.TP
.B --list-db-junk / --kill-db-junk
Sucht/Löscht in der Benutzerdatenbank nach folgendem Müll
(Nichtexistente Gruppen als Mitglieder in Projekten)
.br
.SH OPTION ZUR SUCHE NACH FREMD-DATEIEN
.TP
.B --list-foreign-files
Listet Dateien im Heimatverzeichnis des Users auf, die nicht dem User
gehören. Die Spezialverzeichnisse __austeilen, __tauschen, ... und
deren Inhalt werden NICHT gelistet
.br
.SH OPTIONEN ZUR ANGABE VON USERN:
.TP
Die Auswahl erfolgt anhäufend. Das bedeutet, dass durch Angabe
mehrerer Optionen eine Userliste erzeugt wird, in der kein User
doppelt vorkommt, aber jeder enthalten ist.
.TP
.B -u user1,user2,... / --users user1,user2,... 
.TP
.B -c class1,class2,... / --class class1,class2,...
Als Klasse kann auch <teachers> angegeben werden.
.TP
.B --project project1,project2,...
.TP
.B -r raum1,raum2,... / --room raum1,raum2,...
.TP
.B -s / --students
.TP
.B -w / --workstations 
.TP
.TP
.SH SEE ALSO
.BR sophomorix (8),
.BR sophomorix-teach-in (8),
.BR sophomorix-add (8),
.BR sophomorix-move (8),
.BR sophomorix-print (8),
.BR sophomorix-kill (8),
.BR sophomorix-subclass (8),
.BR sophomorix-project (8),

.\".BR baz (1).
.\".br
.\"You can see the full options of the Programs by calling for example 
.\".IR "sophomrix-janitor -h" ,
.
.SH AUTHOR
Written by <jeffbeck@web.de>.
