.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOPHOMORIX-PRINT 8 "November 30, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sophomorix-print \- Drucken von Benutzeraccount-Daten
.SH SYNOPSIS
.B sophomorix-print
.RI [ options ] 
.br
.SH DESCRIPTION
.B sophomorix-print
.br
Sofern User angelegt wurden werden diejenigen User ausgedruckt, die im
letzten Schritt angelegt wurden. 
.br
Mit den Optionen können User auch klassenweise, ... ausgedruckt
werden.
.br
Die erzeugten Daten finden sich in /var/lib/sophomorix/drucken.
.br 
(später: /var/lib/sophomorix/print)
.br
Im Moment funktioniert sophomorix-print nur ohne Optionen!!
.PP
.SH OPTIONS
.B sophomorix-print
benützt die GNU command line syntax, mit langen Optionen, die mit zwei
Bindestrichen (`-') beginnen:
.TP
.B -h, --help
Kurzübersicht über Optionen
.TP
.B -v, --verbose
Sagt, was das Programm gerade macht (verbose)
.TP
.B -vv, --verbose --verbose
Sagt ungeheuer genau, was das Programm gerade macht (very verbose)
.TP
.B -a , --all, --alle
Erzeugt ein Datei, in der ALLE angelegten User enthalten sind.
.TP
.B -l lehrer, -t lehrer, --lehrer lehrer, --teacher lehrer
Erzeugt eine Datei, in der nur Lehrer enthalten sind.
.TP
.B -k klasse, -c klasse, -g klasse, --klasse klasse
Erzeugt eine Datei, in der nur User enthalten sind, die in der
angegebenen Klasse sind.
.TP
.B -s, --show,
Startet nach dem erzeugen der Datei einen Viewer, um die Datei gleich
anzusehen. (Macht nur Sinn, wenn eine grafische Oberfläche zur
Verfügung steht).
.TP
.B --caller name
Der Dateiname und der Inhalt der Datei enthält den String name. Dies
kann z.B beim Aufruf aus webmin verwendet werden, um den Aufrufenden
Lehrer (caller) mit auszudrucken.
.TP
.SH SEE ALSO
.BR sophomorix (8),
.BR sophomorix-teach-in (8),
.BR sophomorix-add (8),
.BR sophomorix-move (8),
.BR sophomorix-kill (8),
.BR sophomorix-print (8),
.BR sophomorix-user (8),
.BR sophomorix-split (8),
.BR sophomorix-project (8),
.\".BR baz (1).
.\".br
.\"You can see the full options of the Programs by calling for example 
.\".IR "sophomrix-print -h" ,
.
.SH AUTHOR
This manual page was written by <jeffbeck@web.de>.
