.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOPHOMORIX-PROJECT 8 "February 11, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sophomorix-project \- Projekte anlegen und verwalten
.SH SYNOPSIS
.B sophomorix-project
.RI [ options ]
.br
.SH DESCRIPTION
.B Ein von 
.B sophomorix-project
verwaltetes Projekt hat folgende Eigenschaften:
.br
     Name:           Der Name des Projekts (unix groupname), 
.br
                         z.B.:  astro 
.br
     LongName:       Der ausführliche Name des Projekts,  
.br
                         z.B.:  Astronomie-AG-2004
.br
     Admins:         User mit Verwaltungsaufgaben im Projekt
.br
                         z.B.:  bz,kj,roes
.br
     Members:        User, die dem Projekt angehören (Admins gehören 
                     automatisch dazu)
.br
                         z.B.:  muellepe,maierjo
.br
     MemberGroups:   Primäre Gruppen (AdminClass, also Schulklassen und teachers), 
                     deren Mitglieder dem Projekt angehören.
.br
                         z.B.:  12c,7a,teachers
.br
     MemberProjects: Sekundäre Gruppen (Projekte), deren Mitglieder dem Projekt 
angehören.
.br
                         z.B.:  12c,7a,teachers
.br
     AddQuota:       Zuätzliches Festplatten-Quota in MB, das Mitglieder 
                     des Projekts bekommen.
.br
     AddMailQuota:   Zuätzliches Mail-Quota in MB, das Mitglieder 
                     des Projekts bekommen.
.br
                         z.B.:  40
.br
     MaxMembers:     Maximale Anzahl von Mitgliedern, die ein User mit
                     Verwaltungsaufgaben (siehe Admins) einem Projekt 
                     hinzufügen kann. 
                     Diese Grenze gilt nur, wenn AddQuota gesetzt ist.
.br
                         z.B.:  16
     mailalias:      Mailaliase erzeugen (1) oder nicht (0)
     maillist:       MailingListe erzeugen (1) oder nicht (0)
.PP
.SH OPTIONS
.B sophomorix-project
benützt die GNU command line syntax, mit langen Optionen, die mit zwei Bindestrichen (`-') beginnen:
.TP
.B \-h, \-\-help
Kurzübersicht über Optionen, sowie eine Liste der eingelesenen Dateien.
.TP
.B \-v, \-\-verbose
Sagt, was das Programm gerade macht (verbose)
.TP
.B \-i, \-\-info
Informationen über alle Projekte (Übersicht).
.TP
.B \-\-tree
.br
Informationen über alle Projekte und ihre Mitgliedschaften.
.TP
.B \-i -p projektname
Informationen über das Projekt projektname.
.TP
.B \-vv, \-\-verbose \-\-verbose
Sagt ungeheuer genau, was das Programm gerade macht (very verbose)
.TP
.B \-p projektname, \-\-project projektname 
Bearbeitet das vorhandene Projekt projektname.
.TP
.B \-\-create 
Legt das mit -p projektname angegebene Projekt an, falls es noch nicht
existiert.
.TP
.B \-\-kill 
Löscht das mit -p projektname angegebene Projekt. Löscht ebenfalls die
Tausch- und Aufgabenverzeichnisse.
.TP
.B \-\-LongName Projektname(Lang)
Aktualiesiert, bzw. legt das Projekt mit dem LongName Projektname
an. Wird bei einem neuen Projekt kein LongName angegeben, so wird Name
als LongName eingetragen.
.TP
.B \-\-Admins user1,user2,user3, ... 
Trägt die übergebenen User als Verwalter in das Projekt ein. Bisher
vorhandene User werden ersetzt. Werden bei einem neuen Projekt keine
Admins angegeben, so wird root eingetragen.
.br
Wollen sie aus einem Projekt alle Admins entfernen, Müssen sie --Admins "" angeben.
.TP
.B \-\-Members user1,user2,user3, ... 
Trägt die übergebenen User als Mitglieder in das Projekt ein. Bisher
vorhandene User werden ersetzt. Werden bei einem neuen Projekt keine
Members angegeben, so wird nichts eingetragen.
.br
Wollen sie aus einem Projekt alle User entfernen, Müssen sie --Members "" angeben.
.TP
.B \-\-MemberGroups group1,group2,group3, ... 
Trägt die Mitglieder der übergebenen Gruppen als Mitglieder in das
Projekt ein. Bisher vorhandene Gruppen werden ersetzt. Werden
bei einem neuen Projekt keine MemberGroups angegeben, so wird nichts
eingetragen.
.br
Als Gruppen können nur primäre Gruppen angegeben werden, also
sogenannte AdminClasses, die in schueler.txt vorkommen (Also alle vom
Schulverwaltungsprogramm angelegten Klassen)
.br
Wollen sie aus einem Projekt alle Gruppen entfernen, Müssen sie
--MemberGroups "" angeben.
.TP
.B \-\-MemberProjects project1,project2,project3, ... 
Trägt die Mitglieder der übergebenen Projekte als Mitglieder in das
Projekt ein. Bisher vorhandene Projekte werden ersetzt. Werden
bei einem neuen Projekt keine MemberProjects angegeben, so wird nichts
eingetragen.
.br
Wollen sie aus einem Projekt alle MemberProjects entfernen, Müssen sie \
--MemberProjects "" angeben.
.TP
.B \-\-AddQuota quotastring
Trägt den übergebenen quotastring als Zusatzquota in das Projekt ein
und überträgt diese Werte ins System. Der bisher vorhandene
quotastring wird ersetzt. Wird bei einem neuen Projekt kein AddQuota
angegeben, so wird 0 MB eingetragen.
.br
Wie der quotastring aussehen kann siehe:  
.B man sophomorix-quota
.TP
.TP
.B \-\-AddMailQuota number
Trägt die übergebene Zahl(integer) als zusätzliches Mail Quota (in MB)
in das Projekt ein, und überträgt den Wert ins System. Die bisher
vorhandene Zahl wird ersetzt. Wird bei einem neuen Projekt kein
AddMailQuota angegeben, so wird 0 MB eingetragen.
.TP
.B \-\-mailalias
Trägt für alle Mitglieder dieses Projekts einen Mailalias ein
(Standardform: vorname.nachname)
.TP
.B \-\-maillist
Trägt alle Mitglieder dieses Projekts in eine Mailingliste ein. Alle
Mitglieder sind somit unter dem Projektnamen UND dem langen
Projektnamen (LongName) erreichbar.
.TP
.B \-\-MaxMembers anzahl
Trägt anzahl als MaxMembers in das Projekt ein. Die bisher vorhandene
anzahl wird ersetzt. Wird bei einem neuen Projekt keine
MaxMembers angegeben, so wird 0 eingetragen.
.br
Der Eintrag MaxMembers dient zur Begrenzung der vergebenen AddQuota, und ist
nur wirksam, wenn AddQuota nicht 0  ist. Projekte, die mit denen
kein AddQuota gekoppelt ist (AddQuota=0), sind in ihrer Mitgliederanzahl praktisch
unbeschränkt (nur durch eine im Betriebsystem vohandene maximale
Gruppenmitgliedschaftanzahl)
.TP
.B Hinzunehmen und entfernen einzelner members, admins, groups und projects
.TP
.B --addMembers user1,user2,... --project Projekt
Fügt die Mitglieder user1,user2, ... dem Projekt hinzu.
.TP
.B --removeMembers user1,user2,... --project Projekt
Entfernt die Mitglieder user1,user2,... aus dem Projekt. (Es werden
keine Admins entfernt)
.TP
.B --addAdmins user1,user2,... --project Projekt
Fügt die Admins user1,user2,... dem Projekt hinzu.
.TP
.B --removeAdmins user1,user2,... --project Projekt
Entfernt die Admins user1,user2,... aus dem Projekt (auch als
Members). Es werden keine Members entfernt, die nicht auch Admins
sind.
.TP
.B --addMemberGroups gruppe1,gruppe2,... --project Projekt
Fügt die Gruppen gruppe1,gruppe2,... dem Projekt hinzu.
.TP
.B --removeMemberGroups gruppe1,gruppe2,... --project Projekt
Entfernt die Gruppen gruppe1,gruppe2,... aus dem Projekt.
.TP
.B --addMemberProjects project1,project2,... --project Projekt
Fügt die Projekte project1,project2,... dem Projekt hinzu.
.TP
.B --removeProjects project1,project2,... --project Projekt
Entfernt die Projekte project1,project2,... aus dem Projekt.
.TP
.SH SEE ALSO
.BR sophomorix (8),
.BR sophomorix-teach-in (8),
.BR sophomorix-search (8),
.BR sophomorix-add (8),
.BR sophomorix-move (8),
.BR sophomorix-print (8),
.BR sophomorix-kill (8),
.BR sophomorix-subclass (8),
.BR sophomorix-project (8),

.\".BR baz (1).
.\".br
.\"You can see the full options of the Programs by calling for example 
.\".IR "sophomrix-project -h" ,
.
.SH AUTHOR
This manual page was written by <jeffbeck@web.de>.
