.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOPHOMORIX-SETUP 8 "November 30, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sophomorix-setup \- Postinstall-Script von sophomorix-base
.SH SYNOPSIS
.B sophomorix-setup
.br
.SH DESCRIPTION
.B sophomorix-setup
.br
Nach der Installation des Debian-Pakets sophomorix-base wird
sophomorix-setup aufgerufen, um notwendige Verzeichnisse anzulegen.
.PP
.TP
.SH SEE ALSO
.BR sophomorix (8),
.BR sophomorix-teach-in (8),
.BR sophomorix-add (8),
.BR sophomorix-move (8),
.BR sophomorix-kill (8),
.BR sophomorix-print (8),
.BR sophomorix-user (8),
.BR sophomorix-subclass (8),
.BR sophomorix-project (8),
.\".BR baz (1).
.\".br
.\"You can see the full options of the Programs by calling for example 
.\".IR "sophomrix-setup -h" ,
.
.SH AUTHOR
This manual page was written by <jeffbeck@web.de>.
