.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH WORKSTATIONS 5 "October 18, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
/etc/linuxmuster/workstations \- Konfigurationsdatei für den Workstationimport von linuxmuster.net
.br
.SH DESCRIPTION
Um eine Rechnerbezogene Konfiguration der Dienste DNS, DHCP, ... vorzunehmen, werden die Rechner konfiguriert. Außerdem werden von sophomorix Klassenarbeitsaccounts und Computeraccounts (für samba) abgelegt. 

.PP
.SH FELDER
.B Feld 1
.TP
Data goes here
.TP
.SH SEE ALSO
.BR sophomorix-workstation (8),

.\".BR baz (1).
.\".br
.\"You can see the full options of the Programs by calling for example 
.\".IR "sophomrix-useradd -h" ,
.
.SH AUTHOR
Written by <jeffbeck@web.de>.
